// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: muni-service.proto

package muni.model;

public final class MuniService {
  private MuniService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchPersonReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:muni.model.SearchPersonReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return The person.
     */
    muni.model.Model.Person getPerson();
    /**
     * <code>.muni.model.Person person = 1;</code>
     */
    muni.model.Model.PersonOrBuilder getPersonOrBuilder();
  }
  /**
   * <pre>
   *Listed in the order of dependency
   * </pre>
   *
   * Protobuf type {@code muni.model.SearchPersonReq}
   */
  public static final class SearchPersonReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:muni.model.SearchPersonReq)
      SearchPersonReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchPersonReq.newBuilder() to construct.
    private SearchPersonReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchPersonReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchPersonReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchPersonReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              muni.model.Model.Person.Builder subBuilder = null;
              if (person_ != null) {
                subBuilder = person_.toBuilder();
              }
              person_ = input.readMessage(muni.model.Model.Person.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(person_);
                person_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return muni.model.MuniService.internal_static_muni_model_SearchPersonReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return muni.model.MuniService.internal_static_muni_model_SearchPersonReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              muni.model.MuniService.SearchPersonReq.class, muni.model.MuniService.SearchPersonReq.Builder.class);
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    private muni.model.Model.Person person_;
    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return person_ != null;
    }
    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return The person.
     */
    @java.lang.Override
    public muni.model.Model.Person getPerson() {
      return person_ == null ? muni.model.Model.Person.getDefaultInstance() : person_;
    }
    /**
     * <code>.muni.model.Person person = 1;</code>
     */
    @java.lang.Override
    public muni.model.Model.PersonOrBuilder getPersonOrBuilder() {
      return getPerson();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (person_ != null) {
        output.writeMessage(1, getPerson());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (person_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPerson());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof muni.model.MuniService.SearchPersonReq)) {
        return super.equals(obj);
      }
      muni.model.MuniService.SearchPersonReq other = (muni.model.MuniService.SearchPersonReq) obj;

      if (hasPerson() != other.hasPerson()) return false;
      if (hasPerson()) {
        if (!getPerson()
            .equals(other.getPerson())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPerson()) {
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPerson().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static muni.model.MuniService.SearchPersonReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.SearchPersonReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.SearchPersonReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(muni.model.MuniService.SearchPersonReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Listed in the order of dependency
     * </pre>
     *
     * Protobuf type {@code muni.model.SearchPersonReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:muni.model.SearchPersonReq)
        muni.model.MuniService.SearchPersonReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return muni.model.MuniService.internal_static_muni_model_SearchPersonReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return muni.model.MuniService.internal_static_muni_model_SearchPersonReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                muni.model.MuniService.SearchPersonReq.class, muni.model.MuniService.SearchPersonReq.Builder.class);
      }

      // Construct using muni.model.MuniService.SearchPersonReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = null;
        } else {
          person_ = null;
          personBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return muni.model.MuniService.internal_static_muni_model_SearchPersonReq_descriptor;
      }

      @java.lang.Override
      public muni.model.MuniService.SearchPersonReq getDefaultInstanceForType() {
        return muni.model.MuniService.SearchPersonReq.getDefaultInstance();
      }

      @java.lang.Override
      public muni.model.MuniService.SearchPersonReq build() {
        muni.model.MuniService.SearchPersonReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public muni.model.MuniService.SearchPersonReq buildPartial() {
        muni.model.MuniService.SearchPersonReq result = new muni.model.MuniService.SearchPersonReq(this);
        if (personBuilder_ == null) {
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof muni.model.MuniService.SearchPersonReq) {
          return mergeFrom((muni.model.MuniService.SearchPersonReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(muni.model.MuniService.SearchPersonReq other) {
        if (other == muni.model.MuniService.SearchPersonReq.getDefaultInstance()) return this;
        if (other.hasPerson()) {
          mergePerson(other.getPerson());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        muni.model.MuniService.SearchPersonReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (muni.model.MuniService.SearchPersonReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private muni.model.Model.Person person_;
      private com.google.protobuf.SingleFieldBuilderV3<
          muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder> personBuilder_;
      /**
       * <code>.muni.model.Person person = 1;</code>
       * @return Whether the person field is set.
       */
      public boolean hasPerson() {
        return personBuilder_ != null || person_ != null;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       * @return The person.
       */
      public muni.model.Model.Person getPerson() {
        if (personBuilder_ == null) {
          return person_ == null ? muni.model.Model.Person.getDefaultInstance() : person_;
        } else {
          return personBuilder_.getMessage();
        }
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder setPerson(muni.model.Model.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          person_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder setPerson(
          muni.model.Model.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          person_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder mergePerson(muni.model.Model.Person value) {
        if (personBuilder_ == null) {
          if (person_ != null) {
            person_ =
              muni.model.Model.Person.newBuilder(person_).mergeFrom(value).buildPartial();
          } else {
            person_ = value;
          }
          onChanged();
        } else {
          personBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = null;
          onChanged();
        } else {
          person_ = null;
          personBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public muni.model.Model.Person.Builder getPersonBuilder() {
        
        onChanged();
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public muni.model.Model.PersonOrBuilder getPersonOrBuilder() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          return person_ == null ?
              muni.model.Model.Person.getDefaultInstance() : person_;
        }
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder>(
                  getPerson(),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:muni.model.SearchPersonReq)
    }

    // @@protoc_insertion_point(class_scope:muni.model.SearchPersonReq)
    private static final muni.model.MuniService.SearchPersonReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new muni.model.MuniService.SearchPersonReq();
    }

    public static muni.model.MuniService.SearchPersonReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchPersonReq>
        PARSER = new com.google.protobuf.AbstractParser<SearchPersonReq>() {
      @java.lang.Override
      public SearchPersonReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchPersonReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchPersonReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchPersonReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public muni.model.MuniService.SearchPersonReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SearchPersonResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:muni.model.SearchPersonRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    java.util.List<muni.model.Model.Person> 
        getPersonsList();
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    muni.model.Model.Person getPersons(int index);
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    int getPersonsCount();
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    java.util.List<? extends muni.model.Model.PersonOrBuilder> 
        getPersonsOrBuilderList();
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    muni.model.Model.PersonOrBuilder getPersonsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code muni.model.SearchPersonRes}
   */
  public static final class SearchPersonRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:muni.model.SearchPersonRes)
      SearchPersonResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchPersonRes.newBuilder() to construct.
    private SearchPersonRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchPersonRes() {
      persons_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SearchPersonRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchPersonRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                persons_ = new java.util.ArrayList<muni.model.Model.Person>();
                mutable_bitField0_ |= 0x00000001;
              }
              persons_.add(
                  input.readMessage(muni.model.Model.Person.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          persons_ = java.util.Collections.unmodifiableList(persons_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return muni.model.MuniService.internal_static_muni_model_SearchPersonRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return muni.model.MuniService.internal_static_muni_model_SearchPersonRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              muni.model.MuniService.SearchPersonRes.class, muni.model.MuniService.SearchPersonRes.Builder.class);
    }

    public static final int PERSONS_FIELD_NUMBER = 1;
    private java.util.List<muni.model.Model.Person> persons_;
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    @java.lang.Override
    public java.util.List<muni.model.Model.Person> getPersonsList() {
      return persons_;
    }
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends muni.model.Model.PersonOrBuilder> 
        getPersonsOrBuilderList() {
      return persons_;
    }
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    @java.lang.Override
    public int getPersonsCount() {
      return persons_.size();
    }
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    @java.lang.Override
    public muni.model.Model.Person getPersons(int index) {
      return persons_.get(index);
    }
    /**
     * <code>repeated .muni.model.Person persons = 1;</code>
     */
    @java.lang.Override
    public muni.model.Model.PersonOrBuilder getPersonsOrBuilder(
        int index) {
      return persons_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < persons_.size(); i++) {
        output.writeMessage(1, persons_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < persons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, persons_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof muni.model.MuniService.SearchPersonRes)) {
        return super.equals(obj);
      }
      muni.model.MuniService.SearchPersonRes other = (muni.model.MuniService.SearchPersonRes) obj;

      if (!getPersonsList()
          .equals(other.getPersonsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPersonsCount() > 0) {
        hash = (37 * hash) + PERSONS_FIELD_NUMBER;
        hash = (53 * hash) + getPersonsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static muni.model.MuniService.SearchPersonRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.SearchPersonRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.SearchPersonRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(muni.model.MuniService.SearchPersonRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code muni.model.SearchPersonRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:muni.model.SearchPersonRes)
        muni.model.MuniService.SearchPersonResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return muni.model.MuniService.internal_static_muni_model_SearchPersonRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return muni.model.MuniService.internal_static_muni_model_SearchPersonRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                muni.model.MuniService.SearchPersonRes.class, muni.model.MuniService.SearchPersonRes.Builder.class);
      }

      // Construct using muni.model.MuniService.SearchPersonRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPersonsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (personsBuilder_ == null) {
          persons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return muni.model.MuniService.internal_static_muni_model_SearchPersonRes_descriptor;
      }

      @java.lang.Override
      public muni.model.MuniService.SearchPersonRes getDefaultInstanceForType() {
        return muni.model.MuniService.SearchPersonRes.getDefaultInstance();
      }

      @java.lang.Override
      public muni.model.MuniService.SearchPersonRes build() {
        muni.model.MuniService.SearchPersonRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public muni.model.MuniService.SearchPersonRes buildPartial() {
        muni.model.MuniService.SearchPersonRes result = new muni.model.MuniService.SearchPersonRes(this);
        int from_bitField0_ = bitField0_;
        if (personsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            persons_ = java.util.Collections.unmodifiableList(persons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.persons_ = persons_;
        } else {
          result.persons_ = personsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof muni.model.MuniService.SearchPersonRes) {
          return mergeFrom((muni.model.MuniService.SearchPersonRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(muni.model.MuniService.SearchPersonRes other) {
        if (other == muni.model.MuniService.SearchPersonRes.getDefaultInstance()) return this;
        if (personsBuilder_ == null) {
          if (!other.persons_.isEmpty()) {
            if (persons_.isEmpty()) {
              persons_ = other.persons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonsIsMutable();
              persons_.addAll(other.persons_);
            }
            onChanged();
          }
        } else {
          if (!other.persons_.isEmpty()) {
            if (personsBuilder_.isEmpty()) {
              personsBuilder_.dispose();
              personsBuilder_ = null;
              persons_ = other.persons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPersonsFieldBuilder() : null;
            } else {
              personsBuilder_.addAllMessages(other.persons_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        muni.model.MuniService.SearchPersonRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (muni.model.MuniService.SearchPersonRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<muni.model.Model.Person> persons_ =
        java.util.Collections.emptyList();
      private void ensurePersonsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          persons_ = new java.util.ArrayList<muni.model.Model.Person>(persons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder> personsBuilder_;

      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public java.util.List<muni.model.Model.Person> getPersonsList() {
        if (personsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(persons_);
        } else {
          return personsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public int getPersonsCount() {
        if (personsBuilder_ == null) {
          return persons_.size();
        } else {
          return personsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public muni.model.Model.Person getPersons(int index) {
        if (personsBuilder_ == null) {
          return persons_.get(index);
        } else {
          return personsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder setPersons(
          int index, muni.model.Model.Person value) {
        if (personsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonsIsMutable();
          persons_.set(index, value);
          onChanged();
        } else {
          personsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder setPersons(
          int index, muni.model.Model.Person.Builder builderForValue) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.set(index, builderForValue.build());
          onChanged();
        } else {
          personsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder addPersons(muni.model.Model.Person value) {
        if (personsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonsIsMutable();
          persons_.add(value);
          onChanged();
        } else {
          personsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder addPersons(
          int index, muni.model.Model.Person value) {
        if (personsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonsIsMutable();
          persons_.add(index, value);
          onChanged();
        } else {
          personsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder addPersons(
          muni.model.Model.Person.Builder builderForValue) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.add(builderForValue.build());
          onChanged();
        } else {
          personsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder addPersons(
          int index, muni.model.Model.Person.Builder builderForValue) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.add(index, builderForValue.build());
          onChanged();
        } else {
          personsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder addAllPersons(
          java.lang.Iterable<? extends muni.model.Model.Person> values) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, persons_);
          onChanged();
        } else {
          personsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder clearPersons() {
        if (personsBuilder_ == null) {
          persons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public Builder removePersons(int index) {
        if (personsBuilder_ == null) {
          ensurePersonsIsMutable();
          persons_.remove(index);
          onChanged();
        } else {
          personsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public muni.model.Model.Person.Builder getPersonsBuilder(
          int index) {
        return getPersonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public muni.model.Model.PersonOrBuilder getPersonsOrBuilder(
          int index) {
        if (personsBuilder_ == null) {
          return persons_.get(index);  } else {
          return personsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public java.util.List<? extends muni.model.Model.PersonOrBuilder> 
           getPersonsOrBuilderList() {
        if (personsBuilder_ != null) {
          return personsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(persons_);
        }
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public muni.model.Model.Person.Builder addPersonsBuilder() {
        return getPersonsFieldBuilder().addBuilder(
            muni.model.Model.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public muni.model.Model.Person.Builder addPersonsBuilder(
          int index) {
        return getPersonsFieldBuilder().addBuilder(
            index, muni.model.Model.Person.getDefaultInstance());
      }
      /**
       * <code>repeated .muni.model.Person persons = 1;</code>
       */
      public java.util.List<muni.model.Model.Person.Builder> 
           getPersonsBuilderList() {
        return getPersonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder> 
          getPersonsFieldBuilder() {
        if (personsBuilder_ == null) {
          personsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder>(
                  persons_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          persons_ = null;
        }
        return personsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:muni.model.SearchPersonRes)
    }

    // @@protoc_insertion_point(class_scope:muni.model.SearchPersonRes)
    private static final muni.model.MuniService.SearchPersonRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new muni.model.MuniService.SearchPersonRes();
    }

    public static muni.model.MuniService.SearchPersonRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SearchPersonRes>
        PARSER = new com.google.protobuf.AbstractParser<SearchPersonRes>() {
      @java.lang.Override
      public SearchPersonRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchPersonRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchPersonRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchPersonRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public muni.model.MuniService.SearchPersonRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreatePersonReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:muni.model.CreatePersonReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    boolean hasPerson();
    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return The person.
     */
    muni.model.Model.Person getPerson();
    /**
     * <code>.muni.model.Person person = 1;</code>
     */
    muni.model.Model.PersonOrBuilder getPersonOrBuilder();
  }
  /**
   * Protobuf type {@code muni.model.CreatePersonReq}
   */
  public static final class CreatePersonReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:muni.model.CreatePersonReq)
      CreatePersonReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreatePersonReq.newBuilder() to construct.
    private CreatePersonReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreatePersonReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreatePersonReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreatePersonReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              muni.model.Model.Person.Builder subBuilder = null;
              if (person_ != null) {
                subBuilder = person_.toBuilder();
              }
              person_ = input.readMessage(muni.model.Model.Person.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(person_);
                person_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return muni.model.MuniService.internal_static_muni_model_CreatePersonReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return muni.model.MuniService.internal_static_muni_model_CreatePersonReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              muni.model.MuniService.CreatePersonReq.class, muni.model.MuniService.CreatePersonReq.Builder.class);
    }

    public static final int PERSON_FIELD_NUMBER = 1;
    private muni.model.Model.Person person_;
    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return Whether the person field is set.
     */
    @java.lang.Override
    public boolean hasPerson() {
      return person_ != null;
    }
    /**
     * <code>.muni.model.Person person = 1;</code>
     * @return The person.
     */
    @java.lang.Override
    public muni.model.Model.Person getPerson() {
      return person_ == null ? muni.model.Model.Person.getDefaultInstance() : person_;
    }
    /**
     * <code>.muni.model.Person person = 1;</code>
     */
    @java.lang.Override
    public muni.model.Model.PersonOrBuilder getPersonOrBuilder() {
      return getPerson();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (person_ != null) {
        output.writeMessage(1, getPerson());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (person_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPerson());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof muni.model.MuniService.CreatePersonReq)) {
        return super.equals(obj);
      }
      muni.model.MuniService.CreatePersonReq other = (muni.model.MuniService.CreatePersonReq) obj;

      if (hasPerson() != other.hasPerson()) return false;
      if (hasPerson()) {
        if (!getPerson()
            .equals(other.getPerson())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPerson()) {
        hash = (37 * hash) + PERSON_FIELD_NUMBER;
        hash = (53 * hash) + getPerson().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static muni.model.MuniService.CreatePersonReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static muni.model.MuniService.CreatePersonReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.CreatePersonReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static muni.model.MuniService.CreatePersonReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(muni.model.MuniService.CreatePersonReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code muni.model.CreatePersonReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:muni.model.CreatePersonReq)
        muni.model.MuniService.CreatePersonReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return muni.model.MuniService.internal_static_muni_model_CreatePersonReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return muni.model.MuniService.internal_static_muni_model_CreatePersonReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                muni.model.MuniService.CreatePersonReq.class, muni.model.MuniService.CreatePersonReq.Builder.class);
      }

      // Construct using muni.model.MuniService.CreatePersonReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = null;
        } else {
          person_ = null;
          personBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return muni.model.MuniService.internal_static_muni_model_CreatePersonReq_descriptor;
      }

      @java.lang.Override
      public muni.model.MuniService.CreatePersonReq getDefaultInstanceForType() {
        return muni.model.MuniService.CreatePersonReq.getDefaultInstance();
      }

      @java.lang.Override
      public muni.model.MuniService.CreatePersonReq build() {
        muni.model.MuniService.CreatePersonReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public muni.model.MuniService.CreatePersonReq buildPartial() {
        muni.model.MuniService.CreatePersonReq result = new muni.model.MuniService.CreatePersonReq(this);
        if (personBuilder_ == null) {
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof muni.model.MuniService.CreatePersonReq) {
          return mergeFrom((muni.model.MuniService.CreatePersonReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(muni.model.MuniService.CreatePersonReq other) {
        if (other == muni.model.MuniService.CreatePersonReq.getDefaultInstance()) return this;
        if (other.hasPerson()) {
          mergePerson(other.getPerson());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        muni.model.MuniService.CreatePersonReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (muni.model.MuniService.CreatePersonReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private muni.model.Model.Person person_;
      private com.google.protobuf.SingleFieldBuilderV3<
          muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder> personBuilder_;
      /**
       * <code>.muni.model.Person person = 1;</code>
       * @return Whether the person field is set.
       */
      public boolean hasPerson() {
        return personBuilder_ != null || person_ != null;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       * @return The person.
       */
      public muni.model.Model.Person getPerson() {
        if (personBuilder_ == null) {
          return person_ == null ? muni.model.Model.Person.getDefaultInstance() : person_;
        } else {
          return personBuilder_.getMessage();
        }
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder setPerson(muni.model.Model.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          person_ = value;
          onChanged();
        } else {
          personBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder setPerson(
          muni.model.Model.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          person_ = builderForValue.build();
          onChanged();
        } else {
          personBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder mergePerson(muni.model.Model.Person value) {
        if (personBuilder_ == null) {
          if (person_ != null) {
            person_ =
              muni.model.Model.Person.newBuilder(person_).mergeFrom(value).buildPartial();
          } else {
            person_ = value;
          }
          onChanged();
        } else {
          personBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = null;
          onChanged();
        } else {
          person_ = null;
          personBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public muni.model.Model.Person.Builder getPersonBuilder() {
        
        onChanged();
        return getPersonFieldBuilder().getBuilder();
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      public muni.model.Model.PersonOrBuilder getPersonOrBuilder() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilder();
        } else {
          return person_ == null ?
              muni.model.Model.Person.getDefaultInstance() : person_;
        }
      }
      /**
       * <code>.muni.model.Person person = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              muni.model.Model.Person, muni.model.Model.Person.Builder, muni.model.Model.PersonOrBuilder>(
                  getPerson(),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:muni.model.CreatePersonReq)
    }

    // @@protoc_insertion_point(class_scope:muni.model.CreatePersonReq)
    private static final muni.model.MuniService.CreatePersonReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new muni.model.MuniService.CreatePersonReq();
    }

    public static muni.model.MuniService.CreatePersonReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreatePersonReq>
        PARSER = new com.google.protobuf.AbstractParser<CreatePersonReq>() {
      @java.lang.Override
      public CreatePersonReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreatePersonReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreatePersonReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreatePersonReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public muni.model.MuniService.CreatePersonReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_muni_model_SearchPersonReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_muni_model_SearchPersonReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_muni_model_SearchPersonRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_muni_model_SearchPersonRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_muni_model_CreatePersonReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_muni_model_CreatePersonReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022muni-service.proto\022\nmuni.model\032\034google" +
      "/api/annotations.proto\032\033google/protobuf/" +
      "empty.proto\032\020muni-model.proto\"5\n\017SearchP" +
      "ersonReq\022\"\n\006person\030\001 \001(\0132\022.muni.model.Pe" +
      "rson\"6\n\017SearchPersonRes\022#\n\007persons\030\001 \003(\013" +
      "2\022.muni.model.Person\"5\n\017CreatePersonReq\022" +
      "\"\n\006person\030\001 \001(\0132\022.muni.model.Person2t\n\rP" +
      "ersonService\022c\n\006create\022\033.muni.model.Crea" +
      "tePersonReq\032\022.muni.model.Person\"(\202\323\344\223\002\"\"" +
      "\030/mkapp/v1/persons/create:\006person2\330\002\n\rSe" +
      "archService\022n\n\npersonById\022\033.muni.model.S" +
      "earchPersonReq\032\033.muni.model.SearchPerson" +
      "Res\"&\202\323\344\223\002 \"\026/mkapp/v1/persons/byId:\006per" +
      "son\022u\n\016personsSimilar\022\033.muni.model.Searc" +
      "hPersonReq\032\033.muni.model.SearchPersonRes\"" +
      ")\202\323\344\223\002#\"\031/mkapp/v1/persons/similar:\006pers" +
      "on\022`\n\npersonsAll\022\026.google.protobuf.Empty" +
      "\032\033.muni.model.SearchPersonRes\"\035\202\323\344\223\002\027\022\025/" +
      "mkapp/v1/persons/allB\005P\000\210\001\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          muni.model.Model.getDescriptor(),
        });
    internal_static_muni_model_SearchPersonReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_muni_model_SearchPersonReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_muni_model_SearchPersonReq_descriptor,
        new java.lang.String[] { "Person", });
    internal_static_muni_model_SearchPersonRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_muni_model_SearchPersonRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_muni_model_SearchPersonRes_descriptor,
        new java.lang.String[] { "Persons", });
    internal_static_muni_model_CreatePersonReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_muni_model_CreatePersonReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_muni_model_CreatePersonReq_descriptor,
        new java.lang.String[] { "Person", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    muni.model.Model.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
