// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

/**
 * <pre>
 * A case models info need to do some 'business action(s)'
 * Case may be associated with a geo-address
 * Case may have a Person associated with it - 'customer' contact. Org may use this to ask them more info, inform of status etc
 * Case may be handled by specific employee of an organisation - Org contact
 * </pre>
 *
 * Protobuf type {@code corp.model.Case}
 */
public final class Case extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:corp.model.Case)
    CaseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Case.newBuilder() to construct.
  private Case(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Case() {
    status_ = "";
    description_ = "";
    createdByEmployee_ = "";
    tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    typeId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Case();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return corp.model.Model.internal_static_corp_model_Case_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 12:
        return internalGetTypeProps();
      case 10:
        return internalGetXrefs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return corp.model.Model.internal_static_corp_model_Case_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            corp.model.Case.class, corp.model.Case.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 3;
  private long id_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private volatile java.lang.Object status_;
  /**
   * <pre>
   *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
   * </pre>
   *
   * <code>optional string status = 4;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
   * </pre>
   *
   * <code>optional string status = 4;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
   * </pre>
   *
   * <code>optional string status = 4;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 9;
  private volatile java.lang.Object description_;
  /**
   * <code>optional string description = 9;</code>
   * @return Whether the description field is set.
   */
  @java.lang.Override
  public boolean hasDescription() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string description = 9;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>optional string description = 9;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 7;
  private corp.model.PostalAddress address_;
  /**
   * <code>optional .corp.model.PostalAddress address = 7;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .corp.model.PostalAddress address = 7;</code>
   * @return The address.
   */
  @java.lang.Override
  public corp.model.PostalAddress getAddress() {
    return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
  }
  /**
   * <code>optional .corp.model.PostalAddress address = 7;</code>
   */
  @java.lang.Override
  public corp.model.PostalAddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
  }

  public static final int REPORTEDBYCUSTOMER_FIELD_NUMBER = 5;
  private corp.model.Person reportedByCustomer_;
  /**
   * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
   * @return Whether the reportedByCustomer field is set.
   */
  @java.lang.Override
  public boolean hasReportedByCustomer() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
   * @return The reportedByCustomer.
   */
  @java.lang.Override
  public corp.model.Person getReportedByCustomer() {
    return reportedByCustomer_ == null ? corp.model.Person.getDefaultInstance() : reportedByCustomer_;
  }
  /**
   * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
   */
  @java.lang.Override
  public corp.model.PersonOrBuilder getReportedByCustomerOrBuilder() {
    return reportedByCustomer_ == null ? corp.model.Person.getDefaultInstance() : reportedByCustomer_;
  }

  public static final int CREATEDBYEMPLOYEE_FIELD_NUMBER = 6;
  private volatile java.lang.Object createdByEmployee_;
  /**
   * <code>optional string createdByEmployee = 6;</code>
   * @return Whether the createdByEmployee field is set.
   */
  @java.lang.Override
  public boolean hasCreatedByEmployee() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string createdByEmployee = 6;</code>
   * @return The createdByEmployee.
   */
  @java.lang.Override
  public java.lang.String getCreatedByEmployee() {
    java.lang.Object ref = createdByEmployee_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdByEmployee_ = s;
      return s;
    }
  }
  /**
   * <code>optional string createdByEmployee = 6;</code>
   * @return The bytes for createdByEmployee.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedByEmployeeBytes() {
    java.lang.Object ref = createdByEmployee_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdByEmployee_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList tags_;
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int TYPEID_FIELD_NUMBER = 11;
  private volatile java.lang.Object typeId_;
  /**
   * <pre>
   * a unique case type id human understandable string
   * </pre>
   *
   * <code>optional string typeId = 11;</code>
   * @return Whether the typeId field is set.
   */
  @java.lang.Override
  public boolean hasTypeId() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * a unique case type id human understandable string
   * </pre>
   *
   * <code>optional string typeId = 11;</code>
   * @return The typeId.
   */
  @java.lang.Override
  public java.lang.String getTypeId() {
    java.lang.Object ref = typeId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * a unique case type id human understandable string
   * </pre>
   *
   * <code>optional string typeId = 11;</code>
   * @return The bytes for typeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeIdBytes() {
    java.lang.Object ref = typeId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPEPROPS_FIELD_NUMBER = 12;
  private static final class TypePropsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                corp.model.Model.internal_static_corp_model_Case_TypePropsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> typeProps_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetTypeProps() {
    if (typeProps_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          TypePropsDefaultEntryHolder.defaultEntry);
    }
    return typeProps_;
  }

  public int getTypePropsCount() {
    return internalGetTypeProps().getMap().size();
  }
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */

  @java.lang.Override
  public boolean containsTypeProps(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetTypeProps().getMap().containsKey(key);
  }
  /**
   * Use {@link #getTypePropsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getTypeProps() {
    return getTypePropsMap();
  }
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getTypePropsMap() {
    return internalGetTypeProps().getMap();
  }
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */
  @java.lang.Override

  public java.lang.String getTypePropsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTypeProps().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */
  @java.lang.Override

  public java.lang.String getTypePropsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetTypeProps().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int XREFS_FIELD_NUMBER = 10;
  private static final class XrefsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, corp.model.Xref> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, corp.model.Xref>newDefaultInstance(
                corp.model.Model.internal_static_corp_model_Case_XrefsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                corp.model.Xref.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, corp.model.Xref> xrefs_;
  private com.google.protobuf.MapField<java.lang.String, corp.model.Xref>
  internalGetXrefs() {
    if (xrefs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          XrefsDefaultEntryHolder.defaultEntry);
    }
    return xrefs_;
  }

  public int getXrefsCount() {
    return internalGetXrefs().getMap().size();
  }
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */

  @java.lang.Override
  public boolean containsXrefs(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetXrefs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getXrefsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, corp.model.Xref> getXrefs() {
    return getXrefsMap();
  }
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, corp.model.Xref> getXrefsMap() {
    return internalGetXrefs().getMap();
  }
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */
  @java.lang.Override

  public corp.model.Xref getXrefsOrDefault(
      java.lang.String key,
      corp.model.Xref defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, corp.model.Xref> map =
        internalGetXrefs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */
  @java.lang.Override

  public corp.model.Xref getXrefsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, corp.model.Xref> map =
        internalGetXrefs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CREATETIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeMessage(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(3, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, status_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getReportedByCustomer());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, createdByEmployee_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(7, getAddress());
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tags_.getRaw(i));
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, description_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetXrefs(),
        XrefsDefaultEntryHolder.defaultEntry,
        10);
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, typeId_);
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetTypeProps(),
        TypePropsDefaultEntryHolder.defaultEntry,
        12);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, status_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getReportedByCustomer());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, createdByEmployee_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getAddress());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, description_);
    }
    for (java.util.Map.Entry<java.lang.String, corp.model.Xref> entry
         : internalGetXrefs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, corp.model.Xref>
      xrefs__ = XrefsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, xrefs__);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, typeId_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetTypeProps().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      typeProps__ = TypePropsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, typeProps__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof corp.model.Case)) {
      return super.equals(obj);
    }
    corp.model.Case other = (corp.model.Case) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasDescription() != other.hasDescription()) return false;
    if (hasDescription()) {
      if (!getDescription()
          .equals(other.getDescription())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (hasReportedByCustomer() != other.hasReportedByCustomer()) return false;
    if (hasReportedByCustomer()) {
      if (!getReportedByCustomer()
          .equals(other.getReportedByCustomer())) return false;
    }
    if (hasCreatedByEmployee() != other.hasCreatedByEmployee()) return false;
    if (hasCreatedByEmployee()) {
      if (!getCreatedByEmployee()
          .equals(other.getCreatedByEmployee())) return false;
    }
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (hasTypeId() != other.hasTypeId()) return false;
    if (hasTypeId()) {
      if (!getTypeId()
          .equals(other.getTypeId())) return false;
    }
    if (!internalGetTypeProps().equals(
        other.internalGetTypeProps())) return false;
    if (!internalGetXrefs().equals(
        other.internalGetXrefs())) return false;
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasReportedByCustomer()) {
      hash = (37 * hash) + REPORTEDBYCUSTOMER_FIELD_NUMBER;
      hash = (53 * hash) + getReportedByCustomer().hashCode();
    }
    if (hasCreatedByEmployee()) {
      hash = (37 * hash) + CREATEDBYEMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedByEmployee().hashCode();
    }
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    if (hasTypeId()) {
      hash = (37 * hash) + TYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getTypeId().hashCode();
    }
    if (!internalGetTypeProps().getMap().isEmpty()) {
      hash = (37 * hash) + TYPEPROPS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetTypeProps().hashCode();
    }
    if (!internalGetXrefs().getMap().isEmpty()) {
      hash = (37 * hash) + XREFS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetXrefs().hashCode();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static corp.model.Case parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Case parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Case parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Case parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Case parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Case parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Case parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Case parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Case parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static corp.model.Case parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Case parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Case parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(corp.model.Case prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A case models info need to do some 'business action(s)'
   * Case may be associated with a geo-address
   * Case may have a Person associated with it - 'customer' contact. Org may use this to ask them more info, inform of status etc
   * Case may be handled by specific employee of an organisation - Org contact
   * </pre>
   *
   * Protobuf type {@code corp.model.Case}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:corp.model.Case)
      corp.model.CaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return corp.model.Model.internal_static_corp_model_Case_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 12:
          return internalGetTypeProps();
        case 10:
          return internalGetXrefs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 12:
          return internalGetMutableTypeProps();
        case 10:
          return internalGetMutableXrefs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return corp.model.Model.internal_static_corp_model_Case_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              corp.model.Case.class, corp.model.Case.Builder.class);
    }

    // Construct using corp.model.Case.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
        getReportedByCustomerFieldBuilder();
        getCreateTimeFieldBuilder();
        getUpdateTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      description_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        addressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (reportedByCustomerBuilder_ == null) {
        reportedByCustomer_ = null;
      } else {
        reportedByCustomerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      createdByEmployee_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      typeId_ = "";
      bitField0_ = (bitField0_ & ~0x00000080);
      internalGetMutableTypeProps().clear();
      internalGetMutableXrefs().clear();
      if (createTimeBuilder_ == null) {
        createTime_ = null;
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return corp.model.Model.internal_static_corp_model_Case_descriptor;
    }

    @java.lang.Override
    public corp.model.Case getDefaultInstanceForType() {
      return corp.model.Case.getDefaultInstance();
    }

    @java.lang.Override
    public corp.model.Case build() {
      corp.model.Case result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public corp.model.Case buildPartial() {
      corp.model.Case result = new corp.model.Case(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.description_ = description_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (reportedByCustomerBuilder_ == null) {
          result.reportedByCustomer_ = reportedByCustomer_;
        } else {
          result.reportedByCustomer_ = reportedByCustomerBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.createdByEmployee_ = createdByEmployee_;
      if (((bitField0_ & 0x00000040) != 0)) {
        tags_ = tags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.tags_ = tags_;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        to_bitField0_ |= 0x00000040;
      }
      result.typeId_ = typeId_;
      result.typeProps_ = internalGetTypeProps();
      result.typeProps_.makeImmutable();
      result.xrefs_ = internalGetXrefs();
      result.xrefs_.makeImmutable();
      if (((from_bitField0_ & 0x00000400) != 0)) {
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        if (updateTimeBuilder_ == null) {
          result.updateTime_ = updateTime_;
        } else {
          result.updateTime_ = updateTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof corp.model.Case) {
        return mergeFrom((corp.model.Case)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(corp.model.Case other) {
      if (other == corp.model.Case.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasStatus()) {
        bitField0_ |= 0x00000002;
        status_ = other.status_;
        onChanged();
      }
      if (other.hasDescription()) {
        bitField0_ |= 0x00000004;
        description_ = other.description_;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.hasReportedByCustomer()) {
        mergeReportedByCustomer(other.getReportedByCustomer());
      }
      if (other.hasCreatedByEmployee()) {
        bitField0_ |= 0x00000020;
        createdByEmployee_ = other.createdByEmployee_;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (other.hasTypeId()) {
        bitField0_ |= 0x00000080;
        typeId_ = other.typeId_;
        onChanged();
      }
      internalGetMutableTypeProps().mergeFrom(
          other.internalGetTypeProps());
      internalGetMutableXrefs().mergeFrom(
          other.internalGetXrefs());
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 18
            case 24: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 24
            case 34: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getReportedByCustomerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              createdByEmployee_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 58
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 66
            case 74: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 74
            case 82: {
              com.google.protobuf.MapEntry<java.lang.String, corp.model.Xref>
              xrefs__ = input.readMessage(
                  XrefsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableXrefs().getMutableMap().put(
                  xrefs__.getKey(), xrefs__.getValue());
              break;
            } // case 82
            case 90: {
              typeId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 90
            case 98: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              typeProps__ = input.readMessage(
                  TypePropsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableTypeProps().getMutableMap().put(
                  typeProps__.getKey(), typeProps__.getValue());
              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
     * </pre>
     *
     * <code>optional string status = 4;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
     * </pre>
     *
     * <code>optional string status = 4;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
     * </pre>
     *
     * <code>optional string status = 4;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
     * </pre>
     *
     * <code>optional string status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
     * </pre>
     *
     * <code>optional string status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000002);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
     * </pre>
     *
     * <code>optional string status = 4;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      status_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>optional string description = 9;</code>
     * @return Whether the description field is set.
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string description = 9;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string description = 9;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string description = 9;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      bitField0_ = (bitField0_ & ~0x00000004);
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <code>optional string description = 9;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      description_ = value;
      onChanged();
      return this;
    }

    private corp.model.PostalAddress address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder> addressBuilder_;
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     * @return The address.
     */
    public corp.model.PostalAddress getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    public Builder setAddress(corp.model.PostalAddress value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    public Builder setAddress(
        corp.model.PostalAddress.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    public Builder mergeAddress(corp.model.PostalAddress value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            address_ != null &&
            address_ != corp.model.PostalAddress.getDefaultInstance()) {
          address_ =
            corp.model.PostalAddress.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        addressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    public corp.model.PostalAddress.Builder getAddressBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    public corp.model.PostalAddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            corp.model.PostalAddress.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private corp.model.Person reportedByCustomer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.Person, corp.model.Person.Builder, corp.model.PersonOrBuilder> reportedByCustomerBuilder_;
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     * @return Whether the reportedByCustomer field is set.
     */
    public boolean hasReportedByCustomer() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     * @return The reportedByCustomer.
     */
    public corp.model.Person getReportedByCustomer() {
      if (reportedByCustomerBuilder_ == null) {
        return reportedByCustomer_ == null ? corp.model.Person.getDefaultInstance() : reportedByCustomer_;
      } else {
        return reportedByCustomerBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    public Builder setReportedByCustomer(corp.model.Person value) {
      if (reportedByCustomerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reportedByCustomer_ = value;
        onChanged();
      } else {
        reportedByCustomerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    public Builder setReportedByCustomer(
        corp.model.Person.Builder builderForValue) {
      if (reportedByCustomerBuilder_ == null) {
        reportedByCustomer_ = builderForValue.build();
        onChanged();
      } else {
        reportedByCustomerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    public Builder mergeReportedByCustomer(corp.model.Person value) {
      if (reportedByCustomerBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            reportedByCustomer_ != null &&
            reportedByCustomer_ != corp.model.Person.getDefaultInstance()) {
          reportedByCustomer_ =
            corp.model.Person.newBuilder(reportedByCustomer_).mergeFrom(value).buildPartial();
        } else {
          reportedByCustomer_ = value;
        }
        onChanged();
      } else {
        reportedByCustomerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    public Builder clearReportedByCustomer() {
      if (reportedByCustomerBuilder_ == null) {
        reportedByCustomer_ = null;
        onChanged();
      } else {
        reportedByCustomerBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    public corp.model.Person.Builder getReportedByCustomerBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getReportedByCustomerFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    public corp.model.PersonOrBuilder getReportedByCustomerOrBuilder() {
      if (reportedByCustomerBuilder_ != null) {
        return reportedByCustomerBuilder_.getMessageOrBuilder();
      } else {
        return reportedByCustomer_ == null ?
            corp.model.Person.getDefaultInstance() : reportedByCustomer_;
      }
    }
    /**
     * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.Person, corp.model.Person.Builder, corp.model.PersonOrBuilder> 
        getReportedByCustomerFieldBuilder() {
      if (reportedByCustomerBuilder_ == null) {
        reportedByCustomerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            corp.model.Person, corp.model.Person.Builder, corp.model.PersonOrBuilder>(
                getReportedByCustomer(),
                getParentForChildren(),
                isClean());
        reportedByCustomer_ = null;
      }
      return reportedByCustomerBuilder_;
    }

    private java.lang.Object createdByEmployee_ = "";
    /**
     * <code>optional string createdByEmployee = 6;</code>
     * @return Whether the createdByEmployee field is set.
     */
    public boolean hasCreatedByEmployee() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string createdByEmployee = 6;</code>
     * @return The createdByEmployee.
     */
    public java.lang.String getCreatedByEmployee() {
      java.lang.Object ref = createdByEmployee_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdByEmployee_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string createdByEmployee = 6;</code>
     * @return The bytes for createdByEmployee.
     */
    public com.google.protobuf.ByteString
        getCreatedByEmployeeBytes() {
      java.lang.Object ref = createdByEmployee_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdByEmployee_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string createdByEmployee = 6;</code>
     * @param value The createdByEmployee to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedByEmployee(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      createdByEmployee_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string createdByEmployee = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedByEmployee() {
      bitField0_ = (bitField0_ & ~0x00000020);
      createdByEmployee_ = getDefaultInstance().getCreatedByEmployee();
      onChanged();
      return this;
    }
    /**
     * <code>optional string createdByEmployee = 6;</code>
     * @param value The bytes for createdByEmployee to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedByEmployeeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      createdByEmployee_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_.getUnmodifiableView();
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object typeId_ = "";
    /**
     * <pre>
     * a unique case type id human understandable string
     * </pre>
     *
     * <code>optional string typeId = 11;</code>
     * @return Whether the typeId field is set.
     */
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * a unique case type id human understandable string
     * </pre>
     *
     * <code>optional string typeId = 11;</code>
     * @return The typeId.
     */
    public java.lang.String getTypeId() {
      java.lang.Object ref = typeId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * a unique case type id human understandable string
     * </pre>
     *
     * <code>optional string typeId = 11;</code>
     * @return The bytes for typeId.
     */
    public com.google.protobuf.ByteString
        getTypeIdBytes() {
      java.lang.Object ref = typeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * a unique case type id human understandable string
     * </pre>
     *
     * <code>optional string typeId = 11;</code>
     * @param value The typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      typeId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * a unique case type id human understandable string
     * </pre>
     *
     * <code>optional string typeId = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTypeId() {
      bitField0_ = (bitField0_ & ~0x00000080);
      typeId_ = getDefaultInstance().getTypeId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * a unique case type id human understandable string
     * </pre>
     *
     * <code>optional string typeId = 11;</code>
     * @param value The bytes for typeId to set.
     * @return This builder for chaining.
     */
    public Builder setTypeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000080;
      typeId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> typeProps_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTypeProps() {
      if (typeProps_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TypePropsDefaultEntryHolder.defaultEntry);
      }
      return typeProps_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableTypeProps() {
      onChanged();;
      if (typeProps_ == null) {
        typeProps_ = com.google.protobuf.MapField.newMapField(
            TypePropsDefaultEntryHolder.defaultEntry);
      }
      if (!typeProps_.isMutable()) {
        typeProps_ = typeProps_.copy();
      }
      return typeProps_;
    }

    public int getTypePropsCount() {
      return internalGetTypeProps().getMap().size();
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */

    @java.lang.Override
    public boolean containsTypeProps(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetTypeProps().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTypePropsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTypeProps() {
      return getTypePropsMap();
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTypePropsMap() {
      return internalGetTypeProps().getMap();
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */
    @java.lang.Override

    public java.lang.String getTypePropsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTypeProps().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */
    @java.lang.Override

    public java.lang.String getTypePropsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTypeProps().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearTypeProps() {
      internalGetMutableTypeProps().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */

    public Builder removeTypeProps(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableTypeProps().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableTypeProps() {
      return internalGetMutableTypeProps().getMutableMap();
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */
    public Builder putTypeProps(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableTypeProps().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *The key-value that are relevant for each specific case typeId.
     * </pre>
     *
     * <code>map&lt;string, string&gt; typeProps = 12;</code>
     */

    public Builder putAllTypeProps(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableTypeProps().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, corp.model.Xref> xrefs_;
    private com.google.protobuf.MapField<java.lang.String, corp.model.Xref>
    internalGetXrefs() {
      if (xrefs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            XrefsDefaultEntryHolder.defaultEntry);
      }
      return xrefs_;
    }
    private com.google.protobuf.MapField<java.lang.String, corp.model.Xref>
    internalGetMutableXrefs() {
      onChanged();;
      if (xrefs_ == null) {
        xrefs_ = com.google.protobuf.MapField.newMapField(
            XrefsDefaultEntryHolder.defaultEntry);
      }
      if (!xrefs_.isMutable()) {
        xrefs_ = xrefs_.copy();
      }
      return xrefs_;
    }

    public int getXrefsCount() {
      return internalGetXrefs().getMap().size();
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */

    @java.lang.Override
    public boolean containsXrefs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetXrefs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getXrefsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, corp.model.Xref> getXrefs() {
      return getXrefsMap();
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, corp.model.Xref> getXrefsMap() {
      return internalGetXrefs().getMap();
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */
    @java.lang.Override

    public corp.model.Xref getXrefsOrDefault(
        java.lang.String key,
        corp.model.Xref defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, corp.model.Xref> map =
          internalGetXrefs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */
    @java.lang.Override

    public corp.model.Xref getXrefsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, corp.model.Xref> map =
          internalGetXrefs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearXrefs() {
      internalGetMutableXrefs().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */

    public Builder removeXrefs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableXrefs().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, corp.model.Xref>
    getMutableXrefs() {
      return internalGetMutableXrefs().getMutableMap();
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */
    public Builder putXrefs(
        java.lang.String key,
        corp.model.Xref value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableXrefs().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     * Subsystem(s) where case is handled. For info requests this may be null.
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
     */

    public Builder putAllXrefs(
        java.util.Map<java.lang.String, corp.model.Xref> values) {
      internalGetMutableXrefs().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
        onChanged();
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
        onChanged();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
            createTime_ != null &&
            createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          createTime_ =
            com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
        } else {
          createTime_ = value;
        }
        onChanged();
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000400;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder clearCreateTime() {
      if (createTimeBuilder_ == null) {
        createTime_ = null;
        onChanged();
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000400);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private com.google.protobuf.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return The updateTime.
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
            updateTime_ != null &&
            updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          updateTime_ =
            com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
        } else {
          updateTime_ = value;
        }
        onChanged();
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000800;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder clearUpdateTime() {
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
        onChanged();
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000800);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:corp.model.Case)
  }

  // @@protoc_insertion_point(class_scope:corp.model.Case)
  private static final corp.model.Case DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new corp.model.Case();
  }

  public static corp.model.Case getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Case>
      PARSER = new com.google.protobuf.AbstractParser<Case>() {
    @java.lang.Override
    public Case parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Case> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Case> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public corp.model.Case getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

