// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

/**
 * Protobuf type {@code corp.model.CaseList}
 */
public final class CaseList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:corp.model.CaseList)
    CaseListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CaseList.newBuilder() to construct.
  private CaseList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CaseList() {
    cases_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CaseList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return corp.model.Model.internal_static_corp_model_CaseList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return corp.model.Model.internal_static_corp_model_CaseList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            corp.model.CaseList.class, corp.model.CaseList.Builder.class);
  }

  public static final int CASES_FIELD_NUMBER = 1;
  private java.util.List<corp.model.Case> cases_;
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  @java.lang.Override
  public java.util.List<corp.model.Case> getCasesList() {
    return cases_;
  }
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends corp.model.CaseOrBuilder> 
      getCasesOrBuilderList() {
    return cases_;
  }
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  @java.lang.Override
  public int getCasesCount() {
    return cases_.size();
  }
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  @java.lang.Override
  public corp.model.Case getCases(int index) {
    return cases_.get(index);
  }
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  @java.lang.Override
  public corp.model.CaseOrBuilder getCasesOrBuilder(
      int index) {
    return cases_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cases_.size(); i++) {
      output.writeMessage(1, cases_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cases_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cases_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof corp.model.CaseList)) {
      return super.equals(obj);
    }
    corp.model.CaseList other = (corp.model.CaseList) obj;

    if (!getCasesList()
        .equals(other.getCasesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCasesCount() > 0) {
      hash = (37 * hash) + CASES_FIELD_NUMBER;
      hash = (53 * hash) + getCasesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static corp.model.CaseList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.CaseList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.CaseList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.CaseList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.CaseList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.CaseList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.CaseList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.CaseList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.CaseList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static corp.model.CaseList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.CaseList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.CaseList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(corp.model.CaseList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code corp.model.CaseList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:corp.model.CaseList)
      corp.model.CaseListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return corp.model.Model.internal_static_corp_model_CaseList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return corp.model.Model.internal_static_corp_model_CaseList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              corp.model.CaseList.class, corp.model.CaseList.Builder.class);
    }

    // Construct using corp.model.CaseList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (casesBuilder_ == null) {
        cases_ = java.util.Collections.emptyList();
      } else {
        cases_ = null;
        casesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return corp.model.Model.internal_static_corp_model_CaseList_descriptor;
    }

    @java.lang.Override
    public corp.model.CaseList getDefaultInstanceForType() {
      return corp.model.CaseList.getDefaultInstance();
    }

    @java.lang.Override
    public corp.model.CaseList build() {
      corp.model.CaseList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public corp.model.CaseList buildPartial() {
      corp.model.CaseList result = new corp.model.CaseList(this);
      int from_bitField0_ = bitField0_;
      if (casesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cases_ = java.util.Collections.unmodifiableList(cases_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cases_ = cases_;
      } else {
        result.cases_ = casesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof corp.model.CaseList) {
        return mergeFrom((corp.model.CaseList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(corp.model.CaseList other) {
      if (other == corp.model.CaseList.getDefaultInstance()) return this;
      if (casesBuilder_ == null) {
        if (!other.cases_.isEmpty()) {
          if (cases_.isEmpty()) {
            cases_ = other.cases_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCasesIsMutable();
            cases_.addAll(other.cases_);
          }
          onChanged();
        }
      } else {
        if (!other.cases_.isEmpty()) {
          if (casesBuilder_.isEmpty()) {
            casesBuilder_.dispose();
            casesBuilder_ = null;
            cases_ = other.cases_;
            bitField0_ = (bitField0_ & ~0x00000001);
            casesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCasesFieldBuilder() : null;
          } else {
            casesBuilder_.addAllMessages(other.cases_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              corp.model.Case m =
                  input.readMessage(
                      corp.model.Case.parser(),
                      extensionRegistry);
              if (casesBuilder_ == null) {
                ensureCasesIsMutable();
                cases_.add(m);
              } else {
                casesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<corp.model.Case> cases_ =
      java.util.Collections.emptyList();
    private void ensureCasesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cases_ = new java.util.ArrayList<corp.model.Case>(cases_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        corp.model.Case, corp.model.Case.Builder, corp.model.CaseOrBuilder> casesBuilder_;

    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public java.util.List<corp.model.Case> getCasesList() {
      if (casesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cases_);
      } else {
        return casesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public int getCasesCount() {
      if (casesBuilder_ == null) {
        return cases_.size();
      } else {
        return casesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public corp.model.Case getCases(int index) {
      if (casesBuilder_ == null) {
        return cases_.get(index);
      } else {
        return casesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder setCases(
        int index, corp.model.Case value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.set(index, value);
        onChanged();
      } else {
        casesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder setCases(
        int index, corp.model.Case.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.set(index, builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder addCases(corp.model.Case value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.add(value);
        onChanged();
      } else {
        casesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder addCases(
        int index, corp.model.Case value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCasesIsMutable();
        cases_.add(index, value);
        onChanged();
      } else {
        casesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder addCases(
        corp.model.Case.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.add(builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder addCases(
        int index, corp.model.Case.Builder builderForValue) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.add(index, builderForValue.build());
        onChanged();
      } else {
        casesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder addAllCases(
        java.lang.Iterable<? extends corp.model.Case> values) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cases_);
        onChanged();
      } else {
        casesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder clearCases() {
      if (casesBuilder_ == null) {
        cases_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        casesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public Builder removeCases(int index) {
      if (casesBuilder_ == null) {
        ensureCasesIsMutable();
        cases_.remove(index);
        onChanged();
      } else {
        casesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public corp.model.Case.Builder getCasesBuilder(
        int index) {
      return getCasesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public corp.model.CaseOrBuilder getCasesOrBuilder(
        int index) {
      if (casesBuilder_ == null) {
        return cases_.get(index);  } else {
        return casesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public java.util.List<? extends corp.model.CaseOrBuilder> 
         getCasesOrBuilderList() {
      if (casesBuilder_ != null) {
        return casesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cases_);
      }
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public corp.model.Case.Builder addCasesBuilder() {
      return getCasesFieldBuilder().addBuilder(
          corp.model.Case.getDefaultInstance());
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public corp.model.Case.Builder addCasesBuilder(
        int index) {
      return getCasesFieldBuilder().addBuilder(
          index, corp.model.Case.getDefaultInstance());
    }
    /**
     * <code>repeated .corp.model.Case cases = 1;</code>
     */
    public java.util.List<corp.model.Case.Builder> 
         getCasesBuilderList() {
      return getCasesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        corp.model.Case, corp.model.Case.Builder, corp.model.CaseOrBuilder> 
        getCasesFieldBuilder() {
      if (casesBuilder_ == null) {
        casesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            corp.model.Case, corp.model.Case.Builder, corp.model.CaseOrBuilder>(
                cases_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cases_ = null;
      }
      return casesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:corp.model.CaseList)
  }

  // @@protoc_insertion_point(class_scope:corp.model.CaseList)
  private static final corp.model.CaseList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new corp.model.CaseList();
  }

  public static corp.model.CaseList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CaseList>
      PARSER = new com.google.protobuf.AbstractParser<CaseList>() {
    @java.lang.Override
    public CaseList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CaseList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CaseList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public corp.model.CaseList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

