// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface CaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.Case)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
   * </pre>
   *
   * <code>optional string status = 4;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
   * </pre>
   *
   * <code>optional string status = 4;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   *TODO  convert to enum // BACKLOG, INPROGRESS, WAITING, DONE,
   * </pre>
   *
   * <code>optional string status = 4;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>optional string description = 9;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 9;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 9;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional .corp.model.PostalAddress address = 7;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional .corp.model.PostalAddress address = 7;</code>
   * @return The address.
   */
  corp.model.PostalAddress getAddress();
  /**
   * <code>optional .corp.model.PostalAddress address = 7;</code>
   */
  corp.model.PostalAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
   * @return Whether the reportedByCustomer field is set.
   */
  boolean hasReportedByCustomer();
  /**
   * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
   * @return The reportedByCustomer.
   */
  corp.model.Person getReportedByCustomer();
  /**
   * <code>optional .corp.model.Person reportedByCustomer = 5;</code>
   */
  corp.model.PersonOrBuilder getReportedByCustomerOrBuilder();

  /**
   * <code>optional string createdByEmployee = 6;</code>
   * @return Whether the createdByEmployee field is set.
   */
  boolean hasCreatedByEmployee();
  /**
   * <code>optional string createdByEmployee = 6;</code>
   * @return The createdByEmployee.
   */
  java.lang.String getCreatedByEmployee();
  /**
   * <code>optional string createdByEmployee = 6;</code>
   * @return The bytes for createdByEmployee.
   */
  com.google.protobuf.ByteString
      getCreatedByEmployeeBytes();

  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   *store a list of tags that helps routing, categorizing, reporting //TODO Enum?
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * a unique case type id human understandable string
   * </pre>
   *
   * <code>optional string typeId = 11;</code>
   * @return Whether the typeId field is set.
   */
  boolean hasTypeId();
  /**
   * <pre>
   * a unique case type id human understandable string
   * </pre>
   *
   * <code>optional string typeId = 11;</code>
   * @return The typeId.
   */
  java.lang.String getTypeId();
  /**
   * <pre>
   * a unique case type id human understandable string
   * </pre>
   *
   * <code>optional string typeId = 11;</code>
   * @return The bytes for typeId.
   */
  com.google.protobuf.ByteString
      getTypeIdBytes();

  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */
  int getTypePropsCount();
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */
  boolean containsTypeProps(
      java.lang.String key);
  /**
   * Use {@link #getTypePropsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getTypeProps();
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getTypePropsMap();
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */

  /* nullable */
java.lang.String getTypePropsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   *The key-value that are relevant for each specific case typeId.
   * </pre>
   *
   * <code>map&lt;string, string&gt; typeProps = 12;</code>
   */

  java.lang.String getTypePropsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */
  int getXrefsCount();
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */
  boolean containsXrefs(
      java.lang.String key);
  /**
   * Use {@link #getXrefsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, corp.model.Xref>
  getXrefs();
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */
  java.util.Map<java.lang.String, corp.model.Xref>
  getXrefsMap();
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */

  /* nullable */
corp.model.Xref getXrefsOrDefault(
      java.lang.String key,
      /* nullable */
corp.model.Xref defaultValue);
  /**
   * <pre>
   * Subsystem(s) where case is handled. For info requests this may be null.
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 10;</code>
   */

  corp.model.Xref getXrefsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();
}
