// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface CaseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.CaseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  java.util.List<corp.model.Case> 
      getCasesList();
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  corp.model.Case getCases(int index);
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  int getCasesCount();
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  java.util.List<? extends corp.model.CaseOrBuilder> 
      getCasesOrBuilderList();
  /**
   * <code>repeated .corp.model.Case cases = 1;</code>
   */
  corp.model.CaseOrBuilder getCasesOrBuilder(
      int index);
}
