// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface ErrorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.ErrorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .google.protobuf.Any details = 2;</code>
   */
  java.util.List<com.google.protobuf.Any> 
      getDetailsList();
  /**
   * <code>repeated .google.protobuf.Any details = 2;</code>
   */
  com.google.protobuf.Any getDetails(int index);
  /**
   * <code>repeated .google.protobuf.Any details = 2;</code>
   */
  int getDetailsCount();
  /**
   * <code>repeated .google.protobuf.Any details = 2;</code>
   */
  java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
      getDetailsOrBuilderList();
  /**
   * <code>repeated .google.protobuf.Any details = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getDetailsOrBuilder(
      int index);
}
