// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Person_XrefsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Person_XrefsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_ById_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_ById_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Xref_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Xref_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_PostalAddress_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_PostalAddress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Organization_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Organization_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_ErrorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_ErrorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Case_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Case_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Case_TypePropsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Case_TypePropsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_Case_XrefsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_Case_XrefsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_corp_model_CaseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_corp_model_CaseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\0230_corp-models.proto\022\ncorp.model\032\037googl" +
      "e/protobuf/timestamp.proto\032\031google/proto" +
      "buf/any.proto\"\373\003\n\006Person\022\017\n\002id\030\003 \001(\004H\000\210\001" +
      "\001\022\026\n\tfirstName\030\004 \001(\tH\001\210\001\001\022\025\n\010lastName\030\005 " +
      "\001(\tH\002\210\001\001\022\022\n\005email\030\006 \001(\tH\003\210\001\001\022\023\n\006phone1\030\007" +
      " \001(\tH\004\210\001\001\022\023\n\006phone2\030\010 \001(\tH\005\210\001\001\022/\n\007addres" +
      "s\030\t \001(\0132\031.corp.model.PostalAddressH\006\210\001\001\022" +
      ",\n\005xrefs\030\013 \003(\0132\035.corp.model.Person.Xrefs" +
      "Entry\0223\n\ncreateTime\030\001 \001(\0132\032.google.proto" +
      "buf.TimestampH\007\210\001\001\0223\n\nupdateTime\030\002 \001(\0132\032" +
      ".google.protobuf.TimestampH\010\210\001\001\032>\n\nXrefs" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\037\n\005value\030\002 \001(\0132\020.corp" +
      ".model.Xref:\0028\001B\005\n\003_idB\014\n\n_firstNameB\013\n\t" +
      "_lastNameB\010\n\006_emailB\t\n\007_phone1B\t\n\007_phone" +
      "2B\n\n\010_addressB\r\n\013_createTimeB\r\n\013_updateT" +
      "ime\"\022\n\004ById\022\n\n\002id\030\001 \001(\004\"\344\002\n\004Xref\022\017\n\002id\030\006" +
      " \001(\004H\000\210\001\001\022\031\n\014xrefSystemId\030\007 \001(\tH\001\210\001\001\022\023\n\006" +
      "xrefId\030\010 \001(\004H\002\210\001\001\022\023\n\006status\030\t \001(\tH\003\210\001\001\0223" +
      "\n\ncreateTime\030\001 \001(\0132\032.google.protobuf.Tim" +
      "estampH\004\210\001\001\0223\n\nupdateTime\030\002 \001(\0132\032.google" +
      ".protobuf.TimestampH\005\210\001\001\022:\n\021subsysRefres" +
      "hTime\030\003 \001(\0132\032.google.protobuf.TimestampH" +
      "\006\210\001\001B\005\n\003_idB\017\n\r_xrefSystemIdB\t\n\007_xrefIdB" +
      "\t\n\007_statusB\r\n\013_createTimeB\r\n\013_updateTime" +
      "B\024\n\022_subsysRefreshTime\"\273\003\n\rPostalAddress" +
      "\022\017\n\002id\030\003 \001(\004H\000\210\001\001\022\026\n\tstreetNum\030\004 \001(\tH\001\210\001" +
      "\001\022\027\n\nstreetName\030\005 \001(\tH\002\210\001\001\022\021\n\004city\030\006 \001(\t" +
      "H\003\210\001\001\022\025\n\010province\030\007 \001(\tH\004\210\001\001\022\024\n\007country\030" +
      "\010 \001(\tH\005\210\001\001\022\027\n\npostalCode\030\t \001(\tH\006\210\001\001\022\020\n\003l" +
      "at\030\n \001(\001H\007\210\001\001\022\020\n\003lon\030\013 \001(\001H\010\210\001\001\0223\n\ncreat" +
      "eTime\030\001 \001(\0132\032.google.protobuf.TimestampH" +
      "\t\210\001\001\0223\n\nupdateTime\030\002 \001(\0132\032.google.protob" +
      "uf.TimestampH\n\210\001\001B\005\n\003_idB\014\n\n_streetNumB\r" +
      "\n\013_streetNameB\007\n\005_cityB\013\n\t_provinceB\n\n\010_" +
      "countryB\r\n\013_postalCodeB\006\n\004_latB\006\n\004_lonB\r" +
      "\n\013_createTimeB\r\n\013_updateTime\"\311\003\n\014Organiz" +
      "ation\022\017\n\002id\030\003 \001(\004H\000\210\001\001\022\021\n\004name\030\004 \001(\tH\001\210\001" +
      "\001\022\024\n\007website\030\005 \001(\tH\002\210\001\001\022\022\n\005email\030\006 \001(\tH\003" +
      "\210\001\001\022\023\n\006phone1\030\007 \001(\tH\004\210\001\001\022\023\n\006phone2\030\010 \001(\t" +
      "H\005\210\001\001\022/\n\007address\030\t \001(\0132\031.corp.model.Post" +
      "alAddressH\006\210\001\001\022.\n\rcontactPerson\030\n \001(\0132\022." +
      "corp.model.PersonH\007\210\001\001\0223\n\ncreateTime\030\001 \001" +
      "(\0132\032.google.protobuf.TimestampH\010\210\001\001\0223\n\nu" +
      "pdateTime\030\002 \001(\0132\032.google.protobuf.Timest" +
      "ampH\t\210\001\001B\005\n\003_idB\007\n\005_nameB\n\n\010_websiteB\010\n\006" +
      "_emailB\t\n\007_phone1B\t\n\007_phone2B\n\n\010_address" +
      "B\020\n\016_contactPersonB\r\n\013_createTimeB\r\n\013_up" +
      "dateTime\"T\n\tErrorInfo\022\024\n\007message\030\001 \001(\tH\000" +
      "\210\001\001\022%\n\007details\030\002 \003(\0132\024.google.protobuf.A" +
      "nyB\n\n\010_message\"\257\005\n\004Case\022\017\n\002id\030\003 \001(\004H\000\210\001\001" +
      "\022\023\n\006status\030\004 \001(\tH\001\210\001\001\022\030\n\013description\030\t \001" +
      "(\tH\002\210\001\001\022/\n\007address\030\007 \001(\0132\031.corp.model.Po" +
      "stalAddressH\003\210\001\001\0223\n\022reportedByCustomer\030\005" +
      " \001(\0132\022.corp.model.PersonH\004\210\001\001\022\036\n\021created" +
      "ByEmployee\030\006 \001(\tH\005\210\001\001\022\014\n\004tags\030\010 \003(\t\022\023\n\006t" +
      "ypeId\030\013 \001(\tH\006\210\001\001\0222\n\ttypeProps\030\014 \003(\0132\037.co" +
      "rp.model.Case.TypePropsEntry\022*\n\005xrefs\030\n " +
      "\003(\0132\033.corp.model.Case.XrefsEntry\0223\n\ncrea" +
      "teTime\030\001 \001(\0132\032.google.protobuf.Timestamp" +
      "H\007\210\001\001\0223\n\nupdateTime\030\002 \001(\0132\032.google.proto" +
      "buf.TimestampH\010\210\001\001\0320\n\016TypePropsEntry\022\013\n\003" +
      "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032>\n\nXrefsEnt" +
      "ry\022\013\n\003key\030\001 \001(\t\022\037\n\005value\030\002 \001(\0132\020.corp.mo" +
      "del.Xref:\0028\001B\005\n\003_idB\t\n\007_statusB\016\n\014_descr" +
      "iptionB\n\n\010_addressB\025\n\023_reportedByCustome" +
      "rB\024\n\022_createdByEmployeeB\t\n\007_typeIdB\r\n\013_c" +
      "reateTimeB\r\n\013_updateTime\"+\n\010CaseList\022\037\n\005" +
      "cases\030\001 \003(\0132\020.corp.model.CaseB\030\n\ncorp.mo" +
      "delB\005ModelP\001\210\001\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_corp_model_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_corp_model_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Person_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Phone1", "Phone2", "Address", "Xrefs", "CreateTime", "UpdateTime", "Id", "FirstName", "LastName", "Email", "Phone1", "Phone2", "Address", "CreateTime", "UpdateTime", });
    internal_static_corp_model_Person_XrefsEntry_descriptor =
      internal_static_corp_model_Person_descriptor.getNestedTypes().get(0);
    internal_static_corp_model_Person_XrefsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Person_XrefsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_corp_model_ById_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_corp_model_ById_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_ById_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_corp_model_Xref_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_corp_model_Xref_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Xref_descriptor,
        new java.lang.String[] { "Id", "XrefSystemId", "XrefId", "Status", "CreateTime", "UpdateTime", "SubsysRefreshTime", "Id", "XrefSystemId", "XrefId", "Status", "CreateTime", "UpdateTime", "SubsysRefreshTime", });
    internal_static_corp_model_PostalAddress_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_corp_model_PostalAddress_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_PostalAddress_descriptor,
        new java.lang.String[] { "Id", "StreetNum", "StreetName", "City", "Province", "Country", "PostalCode", "Lat", "Lon", "CreateTime", "UpdateTime", "Id", "StreetNum", "StreetName", "City", "Province", "Country", "PostalCode", "Lat", "Lon", "CreateTime", "UpdateTime", });
    internal_static_corp_model_Organization_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_corp_model_Organization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Organization_descriptor,
        new java.lang.String[] { "Id", "Name", "Website", "Email", "Phone1", "Phone2", "Address", "ContactPerson", "CreateTime", "UpdateTime", "Id", "Name", "Website", "Email", "Phone1", "Phone2", "Address", "ContactPerson", "CreateTime", "UpdateTime", });
    internal_static_corp_model_ErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_corp_model_ErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_ErrorInfo_descriptor,
        new java.lang.String[] { "Message", "Details", "Message", });
    internal_static_corp_model_Case_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_corp_model_Case_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Case_descriptor,
        new java.lang.String[] { "Id", "Status", "Description", "Address", "ReportedByCustomer", "CreatedByEmployee", "Tags", "TypeId", "TypeProps", "Xrefs", "CreateTime", "UpdateTime", "Id", "Status", "Description", "Address", "ReportedByCustomer", "CreatedByEmployee", "TypeId", "CreateTime", "UpdateTime", });
    internal_static_corp_model_Case_TypePropsEntry_descriptor =
      internal_static_corp_model_Case_descriptor.getNestedTypes().get(0);
    internal_static_corp_model_Case_TypePropsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Case_TypePropsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_corp_model_Case_XrefsEntry_descriptor =
      internal_static_corp_model_Case_descriptor.getNestedTypes().get(1);
    internal_static_corp_model_Case_XrefsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_Case_XrefsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_corp_model_CaseList_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_corp_model_CaseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_corp_model_CaseList_descriptor,
        new java.lang.String[] { "Cases", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
