// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

/**
 * Protobuf type {@code corp.model.Organization}
 */
public final class Organization extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:corp.model.Organization)
    OrganizationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Organization.newBuilder() to construct.
  private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Organization() {
    name_ = "";
    website_ = "";
    email_ = "";
    phone1_ = "";
    phone2_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Organization();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return corp.model.Model.internal_static_corp_model_Organization_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return corp.model.Model.internal_static_corp_model_Organization_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            corp.model.Organization.class, corp.model.Organization.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 3;
  private long id_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <code>optional string name = 4;</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string name = 4;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>optional string name = 4;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEBSITE_FIELD_NUMBER = 5;
  private volatile java.lang.Object website_;
  /**
   * <code>optional string website = 5;</code>
   * @return Whether the website field is set.
   */
  @java.lang.Override
  public boolean hasWebsite() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string website = 5;</code>
   * @return The website.
   */
  @java.lang.Override
  public java.lang.String getWebsite() {
    java.lang.Object ref = website_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      website_ = s;
      return s;
    }
  }
  /**
   * <code>optional string website = 5;</code>
   * @return The bytes for website.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWebsiteBytes() {
    java.lang.Object ref = website_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      website_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object email_;
  /**
   * <code>optional string email = 6;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string email = 6;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>optional string email = 6;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE1_FIELD_NUMBER = 7;
  private volatile java.lang.Object phone1_;
  /**
   * <code>optional string phone1 = 7;</code>
   * @return Whether the phone1 field is set.
   */
  @java.lang.Override
  public boolean hasPhone1() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The phone1.
   */
  @java.lang.Override
  public java.lang.String getPhone1() {
    java.lang.Object ref = phone1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone1_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The bytes for phone1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhone1Bytes() {
    java.lang.Object ref = phone1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE2_FIELD_NUMBER = 8;
  private volatile java.lang.Object phone2_;
  /**
   * <code>optional string phone2 = 8;</code>
   * @return Whether the phone2 field is set.
   */
  @java.lang.Override
  public boolean hasPhone2() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The phone2.
   */
  @java.lang.Override
  public java.lang.String getPhone2() {
    java.lang.Object ref = phone2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone2_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The bytes for phone2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhone2Bytes() {
    java.lang.Object ref = phone2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 9;
  private corp.model.PostalAddress address_;
  /**
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return The address.
   */
  @java.lang.Override
  public corp.model.PostalAddress getAddress() {
    return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
  }
  /**
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   */
  @java.lang.Override
  public corp.model.PostalAddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
  }

  public static final int CONTACTPERSON_FIELD_NUMBER = 10;
  private corp.model.Person contactPerson_;
  /**
   * <code>optional .corp.model.Person contactPerson = 10;</code>
   * @return Whether the contactPerson field is set.
   */
  @java.lang.Override
  public boolean hasContactPerson() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional .corp.model.Person contactPerson = 10;</code>
   * @return The contactPerson.
   */
  @java.lang.Override
  public corp.model.Person getContactPerson() {
    return contactPerson_ == null ? corp.model.Person.getDefaultInstance() : contactPerson_;
  }
  /**
   * <code>optional .corp.model.Person contactPerson = 10;</code>
   */
  @java.lang.Override
  public corp.model.PersonOrBuilder getContactPersonOrBuilder() {
    return contactPerson_ == null ? corp.model.Person.getDefaultInstance() : contactPerson_;
  }

  public static final int CREATETIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeMessage(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeMessage(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(3, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, website_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, email_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phone1_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, phone2_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(9, getAddress());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(10, getContactPerson());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, website_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, email_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, phone1_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, phone2_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getAddress());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getContactPerson());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof corp.model.Organization)) {
      return super.equals(obj);
    }
    corp.model.Organization other = (corp.model.Organization) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasWebsite() != other.hasWebsite()) return false;
    if (hasWebsite()) {
      if (!getWebsite()
          .equals(other.getWebsite())) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (hasPhone1() != other.hasPhone1()) return false;
    if (hasPhone1()) {
      if (!getPhone1()
          .equals(other.getPhone1())) return false;
    }
    if (hasPhone2() != other.hasPhone2()) return false;
    if (hasPhone2()) {
      if (!getPhone2()
          .equals(other.getPhone2())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (hasContactPerson() != other.hasContactPerson()) return false;
    if (hasContactPerson()) {
      if (!getContactPerson()
          .equals(other.getContactPerson())) return false;
    }
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasWebsite()) {
      hash = (37 * hash) + WEBSITE_FIELD_NUMBER;
      hash = (53 * hash) + getWebsite().hashCode();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasPhone1()) {
      hash = (37 * hash) + PHONE1_FIELD_NUMBER;
      hash = (53 * hash) + getPhone1().hashCode();
    }
    if (hasPhone2()) {
      hash = (37 * hash) + PHONE2_FIELD_NUMBER;
      hash = (53 * hash) + getPhone2().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (hasContactPerson()) {
      hash = (37 * hash) + CONTACTPERSON_FIELD_NUMBER;
      hash = (53 * hash) + getContactPerson().hashCode();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static corp.model.Organization parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Organization parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Organization parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Organization parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Organization parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Organization parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Organization parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Organization parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Organization parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static corp.model.Organization parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Organization parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Organization parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(corp.model.Organization prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code corp.model.Organization}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:corp.model.Organization)
      corp.model.OrganizationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return corp.model.Model.internal_static_corp_model_Organization_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return corp.model.Model.internal_static_corp_model_Organization_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              corp.model.Organization.class, corp.model.Organization.Builder.class);
    }

    // Construct using corp.model.Organization.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
        getContactPersonFieldBuilder();
        getCreateTimeFieldBuilder();
        getUpdateTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      website_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      email_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      phone1_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      phone2_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        addressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      if (contactPersonBuilder_ == null) {
        contactPerson_ = null;
      } else {
        contactPersonBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      if (createTimeBuilder_ == null) {
        createTime_ = null;
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return corp.model.Model.internal_static_corp_model_Organization_descriptor;
    }

    @java.lang.Override
    public corp.model.Organization getDefaultInstanceForType() {
      return corp.model.Organization.getDefaultInstance();
    }

    @java.lang.Override
    public corp.model.Organization build() {
      corp.model.Organization result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public corp.model.Organization buildPartial() {
      corp.model.Organization result = new corp.model.Organization(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.name_ = name_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.website_ = website_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.email_ = email_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.phone1_ = phone1_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.phone2_ = phone2_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        if (contactPersonBuilder_ == null) {
          result.contactPerson_ = contactPerson_;
        } else {
          result.contactPerson_ = contactPersonBuilder_.build();
        }
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        if (updateTimeBuilder_ == null) {
          result.updateTime_ = updateTime_;
        } else {
          result.updateTime_ = updateTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000200;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof corp.model.Organization) {
        return mergeFrom((corp.model.Organization)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(corp.model.Organization other) {
      if (other == corp.model.Organization.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasName()) {
        bitField0_ |= 0x00000002;
        name_ = other.name_;
        onChanged();
      }
      if (other.hasWebsite()) {
        bitField0_ |= 0x00000004;
        website_ = other.website_;
        onChanged();
      }
      if (other.hasEmail()) {
        bitField0_ |= 0x00000008;
        email_ = other.email_;
        onChanged();
      }
      if (other.hasPhone1()) {
        bitField0_ |= 0x00000010;
        phone1_ = other.phone1_;
        onChanged();
      }
      if (other.hasPhone2()) {
        bitField0_ |= 0x00000020;
        phone2_ = other.phone2_;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      if (other.hasContactPerson()) {
        mergeContactPerson(other.getContactPerson());
      }
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 18
            case 24: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 24
            case 34: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            case 42: {
              website_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 42
            case 50: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 50
            case 58: {
              phone1_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 58
            case 66: {
              phone2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  getContactPersonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>optional string name = 4;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string name = 4;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string name = 4;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object website_ = "";
    /**
     * <code>optional string website = 5;</code>
     * @return Whether the website field is set.
     */
    public boolean hasWebsite() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string website = 5;</code>
     * @return The website.
     */
    public java.lang.String getWebsite() {
      java.lang.Object ref = website_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        website_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string website = 5;</code>
     * @return The bytes for website.
     */
    public com.google.protobuf.ByteString
        getWebsiteBytes() {
      java.lang.Object ref = website_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        website_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string website = 5;</code>
     * @param value The website to set.
     * @return This builder for chaining.
     */
    public Builder setWebsite(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      website_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string website = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearWebsite() {
      bitField0_ = (bitField0_ & ~0x00000004);
      website_ = getDefaultInstance().getWebsite();
      onChanged();
      return this;
    }
    /**
     * <code>optional string website = 5;</code>
     * @param value The bytes for website to set.
     * @return This builder for chaining.
     */
    public Builder setWebsiteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      website_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 6;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string email = 6;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 6;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 6;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000008);
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 6;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone1_ = "";
    /**
     * <code>optional string phone1 = 7;</code>
     * @return Whether the phone1 field is set.
     */
    public boolean hasPhone1() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @return The phone1.
     */
    public java.lang.String getPhone1() {
      java.lang.Object ref = phone1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @return The bytes for phone1.
     */
    public com.google.protobuf.ByteString
        getPhone1Bytes() {
      java.lang.Object ref = phone1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @param value The phone1 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      phone1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone1() {
      bitField0_ = (bitField0_ & ~0x00000010);
      phone1_ = getDefaultInstance().getPhone1();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @param value The bytes for phone1 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      phone1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone2_ = "";
    /**
     * <code>optional string phone2 = 8;</code>
     * @return Whether the phone2 field is set.
     */
    public boolean hasPhone2() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @return The phone2.
     */
    public java.lang.String getPhone2() {
      java.lang.Object ref = phone2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @return The bytes for phone2.
     */
    public com.google.protobuf.ByteString
        getPhone2Bytes() {
      java.lang.Object ref = phone2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @param value The phone2 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      phone2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone2() {
      bitField0_ = (bitField0_ & ~0x00000020);
      phone2_ = getDefaultInstance().getPhone2();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @param value The bytes for phone2 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      phone2_ = value;
      onChanged();
      return this;
    }

    private corp.model.PostalAddress address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder> addressBuilder_;
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     * @return The address.
     */
    public corp.model.PostalAddress getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder setAddress(corp.model.PostalAddress value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder setAddress(
        corp.model.PostalAddress.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder mergeAddress(corp.model.PostalAddress value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
            address_ != null &&
            address_ != corp.model.PostalAddress.getDefaultInstance()) {
          address_ =
            corp.model.PostalAddress.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        addressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public corp.model.PostalAddress.Builder getAddressBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public corp.model.PostalAddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            corp.model.PostalAddress.getDefaultInstance() : address_;
      }
    }
    /**
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private corp.model.Person contactPerson_;
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.Person, corp.model.Person.Builder, corp.model.PersonOrBuilder> contactPersonBuilder_;
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     * @return Whether the contactPerson field is set.
     */
    public boolean hasContactPerson() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     * @return The contactPerson.
     */
    public corp.model.Person getContactPerson() {
      if (contactPersonBuilder_ == null) {
        return contactPerson_ == null ? corp.model.Person.getDefaultInstance() : contactPerson_;
      } else {
        return contactPersonBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    public Builder setContactPerson(corp.model.Person value) {
      if (contactPersonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contactPerson_ = value;
        onChanged();
      } else {
        contactPersonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    public Builder setContactPerson(
        corp.model.Person.Builder builderForValue) {
      if (contactPersonBuilder_ == null) {
        contactPerson_ = builderForValue.build();
        onChanged();
      } else {
        contactPersonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    public Builder mergeContactPerson(corp.model.Person value) {
      if (contactPersonBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
            contactPerson_ != null &&
            contactPerson_ != corp.model.Person.getDefaultInstance()) {
          contactPerson_ =
            corp.model.Person.newBuilder(contactPerson_).mergeFrom(value).buildPartial();
        } else {
          contactPerson_ = value;
        }
        onChanged();
      } else {
        contactPersonBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    public Builder clearContactPerson() {
      if (contactPersonBuilder_ == null) {
        contactPerson_ = null;
        onChanged();
      } else {
        contactPersonBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    public corp.model.Person.Builder getContactPersonBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getContactPersonFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    public corp.model.PersonOrBuilder getContactPersonOrBuilder() {
      if (contactPersonBuilder_ != null) {
        return contactPersonBuilder_.getMessageOrBuilder();
      } else {
        return contactPerson_ == null ?
            corp.model.Person.getDefaultInstance() : contactPerson_;
      }
    }
    /**
     * <code>optional .corp.model.Person contactPerson = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.Person, corp.model.Person.Builder, corp.model.PersonOrBuilder> 
        getContactPersonFieldBuilder() {
      if (contactPersonBuilder_ == null) {
        contactPersonBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            corp.model.Person, corp.model.Person.Builder, corp.model.PersonOrBuilder>(
                getContactPerson(),
                getParentForChildren(),
                isClean());
        contactPerson_ = null;
      }
      return contactPersonBuilder_;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
        onChanged();
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
        onChanged();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
            createTime_ != null &&
            createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          createTime_ =
            com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
        } else {
          createTime_ = value;
        }
        onChanged();
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder clearCreateTime() {
      if (createTimeBuilder_ == null) {
        createTime_ = null;
        onChanged();
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private com.google.protobuf.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return The updateTime.
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
            updateTime_ != null &&
            updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          updateTime_ =
            com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
        } else {
          updateTime_ = value;
        }
        onChanged();
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder clearUpdateTime() {
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
        onChanged();
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:corp.model.Organization)
  }

  // @@protoc_insertion_point(class_scope:corp.model.Organization)
  private static final corp.model.Organization DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new corp.model.Organization();
  }

  public static corp.model.Organization getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Organization>
      PARSER = new com.google.protobuf.AbstractParser<Organization>() {
    @java.lang.Override
    public Organization parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Organization> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Organization> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public corp.model.Organization getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

