// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface OrganizationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.Organization)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional string name = 4;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string website = 5;</code>
   * @return Whether the website field is set.
   */
  boolean hasWebsite();
  /**
   * <code>optional string website = 5;</code>
   * @return The website.
   */
  java.lang.String getWebsite();
  /**
   * <code>optional string website = 5;</code>
   * @return The bytes for website.
   */
  com.google.protobuf.ByteString
      getWebsiteBytes();

  /**
   * <code>optional string email = 6;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 6;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 6;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string phone1 = 7;</code>
   * @return Whether the phone1 field is set.
   */
  boolean hasPhone1();
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The phone1.
   */
  java.lang.String getPhone1();
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The bytes for phone1.
   */
  com.google.protobuf.ByteString
      getPhone1Bytes();

  /**
   * <code>optional string phone2 = 8;</code>
   * @return Whether the phone2 field is set.
   */
  boolean hasPhone2();
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The phone2.
   */
  java.lang.String getPhone2();
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The bytes for phone2.
   */
  com.google.protobuf.ByteString
      getPhone2Bytes();

  /**
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return The address.
   */
  corp.model.PostalAddress getAddress();
  /**
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   */
  corp.model.PostalAddressOrBuilder getAddressOrBuilder();

  /**
   * <code>optional .corp.model.Person contactPerson = 10;</code>
   * @return Whether the contactPerson field is set.
   */
  boolean hasContactPerson();
  /**
   * <code>optional .corp.model.Person contactPerson = 10;</code>
   * @return The contactPerson.
   */
  corp.model.Person getContactPerson();
  /**
   * <code>optional .corp.model.Person contactPerson = 10;</code>
   */
  corp.model.PersonOrBuilder getContactPersonOrBuilder();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();
}
