// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

/**
 * <pre>
 * Person, Person::PostalAddress, Person::Xref
 *Person has one address. Person is Xref'd in a list of sub-systems in the organization
 * Not modeling CommunicationChannel, just using a flat email/phone..
 * </pre>
 *
 * Protobuf type {@code corp.model.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:corp.model.Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    firstName_ = "";
    lastName_ = "";
    email_ = "";
    phone1_ = "";
    phone2_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return corp.model.Model.internal_static_corp_model_Person_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 11:
        return internalGetXrefs();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return corp.model.Model.internal_static_corp_model_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            corp.model.Person.class, corp.model.Person.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 3;
  private long id_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int FIRSTNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object firstName_;
  /**
   * <pre>
   * optional added to test hasFirstName()
   * </pre>
   *
   * <code>optional string firstName = 4;</code>
   * @return Whether the firstName field is set.
   */
  @java.lang.Override
  public boolean hasFirstName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * optional added to test hasFirstName()
   * </pre>
   *
   * <code>optional string firstName = 4;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * optional added to test hasFirstName()
   * </pre>
   *
   * <code>optional string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object lastName_;
  /**
   * <code>optional string lastName = 5;</code>
   * @return Whether the lastName field is set.
   */
  @java.lang.Override
  public boolean hasLastName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string lastName = 5;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   *ContactChannels contactChannels = 8;
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   *ContactChannels contactChannels = 8;
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *ContactChannels contactChannels = 8;
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE1_FIELD_NUMBER = 7;
  private volatile java.lang.Object phone1_;
  /**
   * <code>optional string phone1 = 7;</code>
   * @return Whether the phone1 field is set.
   */
  @java.lang.Override
  public boolean hasPhone1() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The phone1.
   */
  @java.lang.Override
  public java.lang.String getPhone1() {
    java.lang.Object ref = phone1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone1_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The bytes for phone1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhone1Bytes() {
    java.lang.Object ref = phone1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE2_FIELD_NUMBER = 8;
  private volatile java.lang.Object phone2_;
  /**
   * <code>optional string phone2 = 8;</code>
   * @return Whether the phone2 field is set.
   */
  @java.lang.Override
  public boolean hasPhone2() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The phone2.
   */
  @java.lang.Override
  public java.lang.String getPhone2() {
    java.lang.Object ref = phone2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phone2_ = s;
      return s;
    }
  }
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The bytes for phone2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhone2Bytes() {
    java.lang.Object ref = phone2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phone2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 9;
  private corp.model.PostalAddress address_;
  /**
   * <pre>
   *For objects no need for optional, hasAddress() works
   * </pre>
   *
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return Whether the address field is set.
   */
  @java.lang.Override
  public boolean hasAddress() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   *For objects no need for optional, hasAddress() works
   * </pre>
   *
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return The address.
   */
  @java.lang.Override
  public corp.model.PostalAddress getAddress() {
    return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
  }
  /**
   * <pre>
   *For objects no need for optional, hasAddress() works
   * </pre>
   *
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   */
  @java.lang.Override
  public corp.model.PostalAddressOrBuilder getAddressOrBuilder() {
    return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
  }

  public static final int XREFS_FIELD_NUMBER = 11;
  private static final class XrefsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, corp.model.Xref> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, corp.model.Xref>newDefaultInstance(
                corp.model.Model.internal_static_corp_model_Person_XrefsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                corp.model.Xref.getDefaultInstance());
  }
  private com.google.protobuf.MapField<
      java.lang.String, corp.model.Xref> xrefs_;
  private com.google.protobuf.MapField<java.lang.String, corp.model.Xref>
  internalGetXrefs() {
    if (xrefs_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          XrefsDefaultEntryHolder.defaultEntry);
    }
    return xrefs_;
  }

  public int getXrefsCount() {
    return internalGetXrefs().getMap().size();
  }
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */

  @java.lang.Override
  public boolean containsXrefs(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetXrefs().getMap().containsKey(key);
  }
  /**
   * Use {@link #getXrefsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, corp.model.Xref> getXrefs() {
    return getXrefsMap();
  }
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, corp.model.Xref> getXrefsMap() {
    return internalGetXrefs().getMap();
  }
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */
  @java.lang.Override

  public corp.model.Xref getXrefsOrDefault(
      java.lang.String key,
      corp.model.Xref defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, corp.model.Xref> map =
        internalGetXrefs().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */
  @java.lang.Override

  public corp.model.Xref getXrefsOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, corp.model.Xref> map =
        internalGetXrefs().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int CREATETIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeMessage(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(3, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, firstName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, lastName_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, email_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, phone1_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, phone2_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(9, getAddress());
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetXrefs(),
        XrefsDefaultEntryHolder.defaultEntry,
        11);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, firstName_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, lastName_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, email_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, phone1_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, phone2_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getAddress());
    }
    for (java.util.Map.Entry<java.lang.String, corp.model.Xref> entry
         : internalGetXrefs().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, corp.model.Xref>
      xrefs__ = XrefsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, xrefs__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof corp.model.Person)) {
      return super.equals(obj);
    }
    corp.model.Person other = (corp.model.Person) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasFirstName() != other.hasFirstName()) return false;
    if (hasFirstName()) {
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
    }
    if (hasLastName() != other.hasLastName()) return false;
    if (hasLastName()) {
      if (!getLastName()
          .equals(other.getLastName())) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (hasPhone1() != other.hasPhone1()) return false;
    if (hasPhone1()) {
      if (!getPhone1()
          .equals(other.getPhone1())) return false;
    }
    if (hasPhone2() != other.hasPhone2()) return false;
    if (hasPhone2()) {
      if (!getPhone2()
          .equals(other.getPhone2())) return false;
    }
    if (hasAddress() != other.hasAddress()) return false;
    if (hasAddress()) {
      if (!getAddress()
          .equals(other.getAddress())) return false;
    }
    if (!internalGetXrefs().equals(
        other.internalGetXrefs())) return false;
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasFirstName()) {
      hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
    }
    if (hasLastName()) {
      hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasPhone1()) {
      hash = (37 * hash) + PHONE1_FIELD_NUMBER;
      hash = (53 * hash) + getPhone1().hashCode();
    }
    if (hasPhone2()) {
      hash = (37 * hash) + PHONE2_FIELD_NUMBER;
      hash = (53 * hash) + getPhone2().hashCode();
    }
    if (hasAddress()) {
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
    }
    if (!internalGetXrefs().getMap().isEmpty()) {
      hash = (37 * hash) + XREFS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetXrefs().hashCode();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static corp.model.Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static corp.model.Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(corp.model.Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Person, Person::PostalAddress, Person::Xref
   *Person has one address. Person is Xref'd in a list of sub-systems in the organization
   * Not modeling CommunicationChannel, just using a flat email/phone..
   * </pre>
   *
   * Protobuf type {@code corp.model.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:corp.model.Person)
      corp.model.PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return corp.model.Model.internal_static_corp_model_Person_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 11:
          return internalGetXrefs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 11:
          return internalGetMutableXrefs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return corp.model.Model.internal_static_corp_model_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              corp.model.Person.class, corp.model.Person.Builder.class);
    }

    // Construct using corp.model.Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressFieldBuilder();
        getCreateTimeFieldBuilder();
        getUpdateTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      firstName_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      lastName_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      email_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      phone1_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      phone2_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      if (addressBuilder_ == null) {
        address_ = null;
      } else {
        addressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      internalGetMutableXrefs().clear();
      if (createTimeBuilder_ == null) {
        createTime_ = null;
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return corp.model.Model.internal_static_corp_model_Person_descriptor;
    }

    @java.lang.Override
    public corp.model.Person getDefaultInstanceForType() {
      return corp.model.Person.getDefaultInstance();
    }

    @java.lang.Override
    public corp.model.Person build() {
      corp.model.Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public corp.model.Person buildPartial() {
      corp.model.Person result = new corp.model.Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.firstName_ = firstName_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.lastName_ = lastName_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.email_ = email_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.phone1_ = phone1_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.phone2_ = phone2_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        to_bitField0_ |= 0x00000040;
      }
      result.xrefs_ = internalGetXrefs();
      result.xrefs_.makeImmutable();
      if (((from_bitField0_ & 0x00000100) != 0)) {
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        if (updateTimeBuilder_ == null) {
          result.updateTime_ = updateTime_;
        } else {
          result.updateTime_ = updateTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000100;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof corp.model.Person) {
        return mergeFrom((corp.model.Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(corp.model.Person other) {
      if (other == corp.model.Person.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasFirstName()) {
        bitField0_ |= 0x00000002;
        firstName_ = other.firstName_;
        onChanged();
      }
      if (other.hasLastName()) {
        bitField0_ |= 0x00000004;
        lastName_ = other.lastName_;
        onChanged();
      }
      if (other.hasEmail()) {
        bitField0_ |= 0x00000008;
        email_ = other.email_;
        onChanged();
      }
      if (other.hasPhone1()) {
        bitField0_ |= 0x00000010;
        phone1_ = other.phone1_;
        onChanged();
      }
      if (other.hasPhone2()) {
        bitField0_ |= 0x00000020;
        phone2_ = other.phone2_;
        onChanged();
      }
      if (other.hasAddress()) {
        mergeAddress(other.getAddress());
      }
      internalGetMutableXrefs().mergeFrom(
          other.internalGetXrefs());
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 18
            case 24: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 24
            case 34: {
              firstName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            case 42: {
              lastName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 42
            case 50: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 50
            case 58: {
              phone1_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 58
            case 66: {
              phone2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getAddressFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 74
            case 90: {
              com.google.protobuf.MapEntry<java.lang.String, corp.model.Xref>
              xrefs__ = input.readMessage(
                  XrefsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableXrefs().getMutableMap().put(
                  xrefs__.getKey(), xrefs__.getValue());
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional uint64 id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <pre>
     * optional added to test hasFirstName()
     * </pre>
     *
     * <code>optional string firstName = 4;</code>
     * @return Whether the firstName field is set.
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * optional added to test hasFirstName()
     * </pre>
     *
     * <code>optional string firstName = 4;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * optional added to test hasFirstName()
     * </pre>
     *
     * <code>optional string firstName = 4;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * optional added to test hasFirstName()
     * </pre>
     *
     * <code>optional string firstName = 4;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      firstName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional added to test hasFirstName()
     * </pre>
     *
     * <code>optional string firstName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      firstName_ = getDefaultInstance().getFirstName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * optional added to test hasFirstName()
     * </pre>
     *
     * <code>optional string firstName = 4;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      firstName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>optional string lastName = 5;</code>
     * @return Whether the lastName field is set.
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string lastName = 5;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string lastName = 5;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string lastName = 5;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      lastName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lastName_ = getDefaultInstance().getLastName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string lastName = 5;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      lastName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     *ContactChannels contactChannels = 8;
     * </pre>
     *
     * <code>optional string email = 6;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *ContactChannels contactChannels = 8;
     * </pre>
     *
     * <code>optional string email = 6;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *ContactChannels contactChannels = 8;
     * </pre>
     *
     * <code>optional string email = 6;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *ContactChannels contactChannels = 8;
     * </pre>
     *
     * <code>optional string email = 6;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ContactChannels contactChannels = 8;
     * </pre>
     *
     * <code>optional string email = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      bitField0_ = (bitField0_ & ~0x00000008);
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *ContactChannels contactChannels = 8;
     * </pre>
     *
     * <code>optional string email = 6;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone1_ = "";
    /**
     * <code>optional string phone1 = 7;</code>
     * @return Whether the phone1 field is set.
     */
    public boolean hasPhone1() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @return The phone1.
     */
    public java.lang.String getPhone1() {
      java.lang.Object ref = phone1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @return The bytes for phone1.
     */
    public com.google.protobuf.ByteString
        getPhone1Bytes() {
      java.lang.Object ref = phone1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @param value The phone1 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      phone1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone1() {
      bitField0_ = (bitField0_ & ~0x00000010);
      phone1_ = getDefaultInstance().getPhone1();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone1 = 7;</code>
     * @param value The bytes for phone1 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000010;
      phone1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object phone2_ = "";
    /**
     * <code>optional string phone2 = 8;</code>
     * @return Whether the phone2 field is set.
     */
    public boolean hasPhone2() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @return The phone2.
     */
    public java.lang.String getPhone2() {
      java.lang.Object ref = phone2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phone2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @return The bytes for phone2.
     */
    public com.google.protobuf.ByteString
        getPhone2Bytes() {
      java.lang.Object ref = phone2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phone2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @param value The phone2 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      phone2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhone2() {
      bitField0_ = (bitField0_ & ~0x00000020);
      phone2_ = getDefaultInstance().getPhone2();
      onChanged();
      return this;
    }
    /**
     * <code>optional string phone2 = 8;</code>
     * @param value The bytes for phone2 to set.
     * @return This builder for chaining.
     */
    public Builder setPhone2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000020;
      phone2_ = value;
      onChanged();
      return this;
    }

    private corp.model.PostalAddress address_;
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder> addressBuilder_;
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     * @return The address.
     */
    public corp.model.PostalAddress getAddress() {
      if (addressBuilder_ == null) {
        return address_ == null ? corp.model.PostalAddress.getDefaultInstance() : address_;
      } else {
        return addressBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder setAddress(corp.model.PostalAddress value) {
      if (addressBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        address_ = value;
        onChanged();
      } else {
        addressBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder setAddress(
        corp.model.PostalAddress.Builder builderForValue) {
      if (addressBuilder_ == null) {
        address_ = builderForValue.build();
        onChanged();
      } else {
        addressBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder mergeAddress(corp.model.PostalAddress value) {
      if (addressBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
            address_ != null &&
            address_ != corp.model.PostalAddress.getDefaultInstance()) {
          address_ =
            corp.model.PostalAddress.newBuilder(address_).mergeFrom(value).buildPartial();
        } else {
          address_ = value;
        }
        onChanged();
      } else {
        addressBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public Builder clearAddress() {
      if (addressBuilder_ == null) {
        address_ = null;
        onChanged();
      } else {
        addressBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public corp.model.PostalAddress.Builder getAddressBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getAddressFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    public corp.model.PostalAddressOrBuilder getAddressOrBuilder() {
      if (addressBuilder_ != null) {
        return addressBuilder_.getMessageOrBuilder();
      } else {
        return address_ == null ?
            corp.model.PostalAddress.getDefaultInstance() : address_;
      }
    }
    /**
     * <pre>
     *For objects no need for optional, hasAddress() works
     * </pre>
     *
     * <code>optional .corp.model.PostalAddress address = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder> 
        getAddressFieldBuilder() {
      if (addressBuilder_ == null) {
        addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            corp.model.PostalAddress, corp.model.PostalAddress.Builder, corp.model.PostalAddressOrBuilder>(
                getAddress(),
                getParentForChildren(),
                isClean());
        address_ = null;
      }
      return addressBuilder_;
    }

    private com.google.protobuf.MapField<
        java.lang.String, corp.model.Xref> xrefs_;
    private com.google.protobuf.MapField<java.lang.String, corp.model.Xref>
    internalGetXrefs() {
      if (xrefs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            XrefsDefaultEntryHolder.defaultEntry);
      }
      return xrefs_;
    }
    private com.google.protobuf.MapField<java.lang.String, corp.model.Xref>
    internalGetMutableXrefs() {
      onChanged();;
      if (xrefs_ == null) {
        xrefs_ = com.google.protobuf.MapField.newMapField(
            XrefsDefaultEntryHolder.defaultEntry);
      }
      if (!xrefs_.isMutable()) {
        xrefs_ = xrefs_.copy();
      }
      return xrefs_;
    }

    public int getXrefsCount() {
      return internalGetXrefs().getMap().size();
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */

    @java.lang.Override
    public boolean containsXrefs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetXrefs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getXrefsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, corp.model.Xref> getXrefs() {
      return getXrefsMap();
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, corp.model.Xref> getXrefsMap() {
      return internalGetXrefs().getMap();
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */
    @java.lang.Override

    public corp.model.Xref getXrefsOrDefault(
        java.lang.String key,
        corp.model.Xref defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, corp.model.Xref> map =
          internalGetXrefs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */
    @java.lang.Override

    public corp.model.Xref getXrefsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, corp.model.Xref> map =
          internalGetXrefs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearXrefs() {
      internalGetMutableXrefs().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */

    public Builder removeXrefs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableXrefs().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, corp.model.Xref>
    getMutableXrefs() {
      return internalGetMutableXrefs().getMutableMap();
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */
    public Builder putXrefs(
        java.lang.String key,
        corp.model.Xref value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) {
  throw new NullPointerException("map value");
}

      internalGetMutableXrefs().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <pre>
     *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
     * </pre>
     *
     * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
     */

    public Builder putAllXrefs(
        java.util.Map<java.lang.String, corp.model.Xref> values) {
      internalGetMutableXrefs().getMutableMap()
          .putAll(values);
      return this;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
        onChanged();
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
        onChanged();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
            createTime_ != null &&
            createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          createTime_ =
            com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
        } else {
          createTime_ = value;
        }
        onChanged();
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000100;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder clearCreateTime() {
      if (createTimeBuilder_ == null) {
        createTime_ = null;
        onChanged();
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private com.google.protobuf.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return The updateTime.
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
            updateTime_ != null &&
            updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          updateTime_ =
            com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
        } else {
          updateTime_ = value;
        }
        onChanged();
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder clearUpdateTime() {
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
        onChanged();
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return getUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:corp.model.Person)
  }

  // @@protoc_insertion_point(class_scope:corp.model.Person)
  private static final corp.model.Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new corp.model.Person();
  }

  public static corp.model.Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public corp.model.Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

