// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * optional added to test hasFirstName()
   * </pre>
   *
   * <code>optional string firstName = 4;</code>
   * @return Whether the firstName field is set.
   */
  boolean hasFirstName();
  /**
   * <pre>
   * optional added to test hasFirstName()
   * </pre>
   *
   * <code>optional string firstName = 4;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <pre>
   * optional added to test hasFirstName()
   * </pre>
   *
   * <code>optional string firstName = 4;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>optional string lastName = 5;</code>
   * @return Whether the lastName field is set.
   */
  boolean hasLastName();
  /**
   * <code>optional string lastName = 5;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>optional string lastName = 5;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <pre>
   *ContactChannels contactChannels = 8;
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <pre>
   *ContactChannels contactChannels = 8;
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   *ContactChannels contactChannels = 8;
   * </pre>
   *
   * <code>optional string email = 6;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string phone1 = 7;</code>
   * @return Whether the phone1 field is set.
   */
  boolean hasPhone1();
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The phone1.
   */
  java.lang.String getPhone1();
  /**
   * <code>optional string phone1 = 7;</code>
   * @return The bytes for phone1.
   */
  com.google.protobuf.ByteString
      getPhone1Bytes();

  /**
   * <code>optional string phone2 = 8;</code>
   * @return Whether the phone2 field is set.
   */
  boolean hasPhone2();
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The phone2.
   */
  java.lang.String getPhone2();
  /**
   * <code>optional string phone2 = 8;</code>
   * @return The bytes for phone2.
   */
  com.google.protobuf.ByteString
      getPhone2Bytes();

  /**
   * <pre>
   *For objects no need for optional, hasAddress() works
   * </pre>
   *
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <pre>
   *For objects no need for optional, hasAddress() works
   * </pre>
   *
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   * @return The address.
   */
  corp.model.PostalAddress getAddress();
  /**
   * <pre>
   *For objects no need for optional, hasAddress() works
   * </pre>
   *
   * <code>optional .corp.model.PostalAddress address = 9;</code>
   */
  corp.model.PostalAddressOrBuilder getAddressOrBuilder();

  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */
  int getXrefsCount();
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */
  boolean containsXrefs(
      java.lang.String key);
  /**
   * Use {@link #getXrefsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, corp.model.Xref>
  getXrefs();
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */
  java.util.Map<java.lang.String, corp.model.Xref>
  getXrefsMap();
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */

  /* nullable */
corp.model.Xref getXrefsOrDefault(
      java.lang.String key,
      /* nullable */
corp.model.Xref defaultValue);
  /**
   * <pre>
   *optional  bool dirty = 10 [default = false];//for boolean getDirty() default is enough, no need for optional
   * </pre>
   *
   * <code>map&lt;string, .corp.model.Xref&gt; xrefs = 11;</code>
   */

  corp.model.Xref getXrefsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();
}
