// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface PostalAddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.PostalAddress)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 id = 3;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional uint64 id = 3;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>optional string streetNum = 4;</code>
   * @return Whether the streetNum field is set.
   */
  boolean hasStreetNum();
  /**
   * <code>optional string streetNum = 4;</code>
   * @return The streetNum.
   */
  java.lang.String getStreetNum();
  /**
   * <code>optional string streetNum = 4;</code>
   * @return The bytes for streetNum.
   */
  com.google.protobuf.ByteString
      getStreetNumBytes();

  /**
   * <code>optional string streetName = 5;</code>
   * @return Whether the streetName field is set.
   */
  boolean hasStreetName();
  /**
   * <code>optional string streetName = 5;</code>
   * @return The streetName.
   */
  java.lang.String getStreetName();
  /**
   * <code>optional string streetName = 5;</code>
   * @return The bytes for streetName.
   */
  com.google.protobuf.ByteString
      getStreetNameBytes();

  /**
   * <code>optional string city = 6;</code>
   * @return Whether the city field is set.
   */
  boolean hasCity();
  /**
   * <code>optional string city = 6;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>optional string city = 6;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>optional string province = 7;</code>
   * @return Whether the province field is set.
   */
  boolean hasProvince();
  /**
   * <code>optional string province = 7;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <code>optional string province = 7;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <code>optional string country = 8;</code>
   * @return Whether the country field is set.
   */
  boolean hasCountry();
  /**
   * <code>optional string country = 8;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <code>optional string country = 8;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <code>optional string postalCode = 9;</code>
   * @return Whether the postalCode field is set.
   */
  boolean hasPostalCode();
  /**
   * <code>optional string postalCode = 9;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <code>optional string postalCode = 9;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <pre>
   *geo
   * </pre>
   *
   * <code>optional double lat = 10;</code>
   * @return Whether the lat field is set.
   */
  boolean hasLat();
  /**
   * <pre>
   *geo
   * </pre>
   *
   * <code>optional double lat = 10;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>optional double lon = 11;</code>
   * @return Whether the lon field is set.
   */
  boolean hasLon();
  /**
   * <code>optional double lon = 11;</code>
   * @return The lon.
   */
  double getLon();

  /**
   * <pre>
   *optional  bool dirty = 12 [default=false];
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   *optional  bool dirty = 12 [default=false];
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   *optional  bool dirty = 12 [default=false];
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();
}
