// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

public interface XrefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:corp.model.Xref)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * golden personId, or, caseId
   * </pre>
   *
   * <code>optional uint64 id = 6;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <pre>
   * golden personId, or, caseId
   * </pre>
   *
   * <code>optional uint64 id = 6;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * {"AMANDA"|"HANSEN" ...}
   * </pre>
   *
   * <code>optional string xrefSystemId = 7;</code>
   * @return Whether the xrefSystemId field is set.
   */
  boolean hasXrefSystemId();
  /**
   * <pre>
   * {"AMANDA"|"HANSEN" ...}
   * </pre>
   *
   * <code>optional string xrefSystemId = 7;</code>
   * @return The xrefSystemId.
   */
  java.lang.String getXrefSystemId();
  /**
   * <pre>
   * {"AMANDA"|"HANSEN" ...}
   * </pre>
   *
   * <code>optional string xrefSystemId = 7;</code>
   * @return The bytes for xrefSystemId.
   */
  com.google.protobuf.ByteString
      getXrefSystemIdBytes();

  /**
   * <pre>
   *subsystem personid or caseid
   * </pre>
   *
   * <code>optional uint64 xrefId = 8;</code>
   * @return Whether the xrefId field is set.
   */
  boolean hasXrefId();
  /**
   * <pre>
   *subsystem personid or caseid
   * </pre>
   *
   * <code>optional uint64 xrefId = 8;</code>
   * @return The xrefId.
   */
  long getXrefId();

  /**
   * <pre>
   * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
   * </pre>
   *
   * <code>optional string status = 9;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
   * </pre>
   *
   * <code>optional string status = 9;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
   * </pre>
   *
   * <code>optional string status = 9;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   * <pre>
   *Output only  - updated by person/{id}/xref/{subsysId}/sync
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
   * @return Whether the subsysRefreshTime field is set.
   */
  boolean hasSubsysRefreshTime();
  /**
   * <pre>
   *Output only  - updated by person/{id}/xref/{subsysId}/sync
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
   * @return The subsysRefreshTime.
   */
  com.google.protobuf.Timestamp getSubsysRefreshTime();
  /**
   * <pre>
   *Output only  - updated by person/{id}/xref/{subsysId}/sync
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getSubsysRefreshTimeOrBuilder();
}
