// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 0_corp-models.proto

package corp.model;

/**
 * <pre>
 * Person -&gt; Xref of Person , Case -&gt; Xref if Case
 * </pre>
 *
 * Protobuf type {@code corp.model.Xref}
 */
public final class Xref extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:corp.model.Xref)
    XrefOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Xref.newBuilder() to construct.
  private Xref(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Xref() {
    xrefSystemId_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Xref();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return corp.model.Model.internal_static_corp_model_Xref_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return corp.model.Model.internal_static_corp_model_Xref_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            corp.model.Xref.class, corp.model.Xref.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 6;
  private long id_;
  /**
   * <pre>
   * golden personId, or, caseId
   * </pre>
   *
   * <code>optional uint64 id = 6;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * golden personId, or, caseId
   * </pre>
   *
   * <code>optional uint64 id = 6;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int XREFSYSTEMID_FIELD_NUMBER = 7;
  private volatile java.lang.Object xrefSystemId_;
  /**
   * <pre>
   * {"AMANDA"|"HANSEN" ...}
   * </pre>
   *
   * <code>optional string xrefSystemId = 7;</code>
   * @return Whether the xrefSystemId field is set.
   */
  @java.lang.Override
  public boolean hasXrefSystemId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * {"AMANDA"|"HANSEN" ...}
   * </pre>
   *
   * <code>optional string xrefSystemId = 7;</code>
   * @return The xrefSystemId.
   */
  @java.lang.Override
  public java.lang.String getXrefSystemId() {
    java.lang.Object ref = xrefSystemId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      xrefSystemId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * {"AMANDA"|"HANSEN" ...}
   * </pre>
   *
   * <code>optional string xrefSystemId = 7;</code>
   * @return The bytes for xrefSystemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getXrefSystemIdBytes() {
    java.lang.Object ref = xrefSystemId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      xrefSystemId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int XREFID_FIELD_NUMBER = 8;
  private long xrefId_;
  /**
   * <pre>
   *subsystem personid or caseid
   * </pre>
   *
   * <code>optional uint64 xrefId = 8;</code>
   * @return Whether the xrefId field is set.
   */
  @java.lang.Override
  public boolean hasXrefId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   *subsystem personid or caseid
   * </pre>
   *
   * <code>optional uint64 xrefId = 8;</code>
   * @return The xrefId.
   */
  @java.lang.Override
  public long getXrefId() {
    return xrefId_;
  }

  public static final int STATUS_FIELD_NUMBER = 9;
  private volatile java.lang.Object status_;
  /**
   * <pre>
   * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
   * </pre>
   *
   * <code>optional string status = 9;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
   * </pre>
   *
   * <code>optional string status = 9;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
   * </pre>
   *
   * <code>optional string status = 9;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATETIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int UPDATETIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp updateTime_;
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return Whether the updateTime field is set.
   */
  @java.lang.Override
  public boolean hasUpdateTime() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   * @return The updateTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdateTime() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }
  /**
   * <pre>
   *Output only
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
    return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
  }

  public static final int SUBSYSREFRESHTIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp subsysRefreshTime_;
  /**
   * <pre>
   *Output only  - updated by person/{id}/xref/{subsysId}/sync
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
   * @return Whether the subsysRefreshTime field is set.
   */
  @java.lang.Override
  public boolean hasSubsysRefreshTime() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   *Output only  - updated by person/{id}/xref/{subsysId}/sync
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
   * @return The subsysRefreshTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getSubsysRefreshTime() {
    return subsysRefreshTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : subsysRefreshTime_;
  }
  /**
   * <pre>
   *Output only  - updated by person/{id}/xref/{subsysId}/sync
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getSubsysRefreshTimeOrBuilder() {
    return subsysRefreshTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : subsysRefreshTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(3, getSubsysRefreshTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeUInt64(6, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, xrefSystemId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt64(8, xrefId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCreateTime());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdateTime());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSubsysRefreshTime());
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, xrefSystemId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, xrefId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof corp.model.Xref)) {
      return super.equals(obj);
    }
    corp.model.Xref other = (corp.model.Xref) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (getId()
          != other.getId()) return false;
    }
    if (hasXrefSystemId() != other.hasXrefSystemId()) return false;
    if (hasXrefSystemId()) {
      if (!getXrefSystemId()
          .equals(other.getXrefSystemId())) return false;
    }
    if (hasXrefId() != other.hasXrefId()) return false;
    if (hasXrefId()) {
      if (getXrefId()
          != other.getXrefId()) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (hasUpdateTime() != other.hasUpdateTime()) return false;
    if (hasUpdateTime()) {
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
    }
    if (hasSubsysRefreshTime() != other.hasSubsysRefreshTime()) return false;
    if (hasSubsysRefreshTime()) {
      if (!getSubsysRefreshTime()
          .equals(other.getSubsysRefreshTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
    }
    if (hasXrefSystemId()) {
      hash = (37 * hash) + XREFSYSTEMID_FIELD_NUMBER;
      hash = (53 * hash) + getXrefSystemId().hashCode();
    }
    if (hasXrefId()) {
      hash = (37 * hash) + XREFID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getXrefId());
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (hasUpdateTime()) {
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
    }
    if (hasSubsysRefreshTime()) {
      hash = (37 * hash) + SUBSYSREFRESHTIME_FIELD_NUMBER;
      hash = (53 * hash) + getSubsysRefreshTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static corp.model.Xref parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Xref parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Xref parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Xref parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Xref parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static corp.model.Xref parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static corp.model.Xref parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Xref parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Xref parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static corp.model.Xref parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static corp.model.Xref parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static corp.model.Xref parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(corp.model.Xref prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Person -&gt; Xref of Person , Case -&gt; Xref if Case
   * </pre>
   *
   * Protobuf type {@code corp.model.Xref}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:corp.model.Xref)
      corp.model.XrefOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return corp.model.Model.internal_static_corp_model_Xref_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return corp.model.Model.internal_static_corp_model_Xref_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              corp.model.Xref.class, corp.model.Xref.Builder.class);
    }

    // Construct using corp.model.Xref.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCreateTimeFieldBuilder();
        getUpdateTimeFieldBuilder();
        getSubsysRefreshTimeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      xrefSystemId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      xrefId_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      if (createTimeBuilder_ == null) {
        createTime_ = null;
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      if (subsysRefreshTimeBuilder_ == null) {
        subsysRefreshTime_ = null;
      } else {
        subsysRefreshTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return corp.model.Model.internal_static_corp_model_Xref_descriptor;
    }

    @java.lang.Override
    public corp.model.Xref getDefaultInstanceForType() {
      return corp.model.Xref.getDefaultInstance();
    }

    @java.lang.Override
    public corp.model.Xref build() {
      corp.model.Xref result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public corp.model.Xref buildPartial() {
      corp.model.Xref result = new corp.model.Xref(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.xrefSystemId_ = xrefSystemId_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.xrefId_ = xrefId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        if (createTimeBuilder_ == null) {
          result.createTime_ = createTime_;
        } else {
          result.createTime_ = createTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        if (updateTimeBuilder_ == null) {
          result.updateTime_ = updateTime_;
        } else {
          result.updateTime_ = updateTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        if (subsysRefreshTimeBuilder_ == null) {
          result.subsysRefreshTime_ = subsysRefreshTime_;
        } else {
          result.subsysRefreshTime_ = subsysRefreshTimeBuilder_.build();
        }
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof corp.model.Xref) {
        return mergeFrom((corp.model.Xref)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(corp.model.Xref other) {
      if (other == corp.model.Xref.getDefaultInstance()) return this;
      if (other.hasId()) {
        setId(other.getId());
      }
      if (other.hasXrefSystemId()) {
        bitField0_ |= 0x00000002;
        xrefSystemId_ = other.xrefSystemId_;
        onChanged();
      }
      if (other.hasXrefId()) {
        setXrefId(other.getXrefId());
      }
      if (other.hasStatus()) {
        bitField0_ |= 0x00000008;
        status_ = other.status_;
        onChanged();
      }
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (other.hasUpdateTime()) {
        mergeUpdateTime(other.getUpdateTime());
      }
      if (other.hasSubsysRefreshTime()) {
        mergeSubsysRefreshTime(other.getSubsysRefreshTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getUpdateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSubsysRefreshTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 26
            case 48: {
              id_ = input.readUInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 48
            case 58: {
              xrefSystemId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 58
            case 64: {
              xrefId_ = input.readUInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 64
            case 74: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     * golden personId, or, caseId
     * </pre>
     *
     * <code>optional uint64 id = 6;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * golden personId, or, caseId
     * </pre>
     *
     * <code>optional uint64 id = 6;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * golden personId, or, caseId
     * </pre>
     *
     * <code>optional uint64 id = 6;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      bitField0_ |= 0x00000001;
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * golden personId, or, caseId
     * </pre>
     *
     * <code>optional uint64 id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object xrefSystemId_ = "";
    /**
     * <pre>
     * {"AMANDA"|"HANSEN" ...}
     * </pre>
     *
     * <code>optional string xrefSystemId = 7;</code>
     * @return Whether the xrefSystemId field is set.
     */
    public boolean hasXrefSystemId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * {"AMANDA"|"HANSEN" ...}
     * </pre>
     *
     * <code>optional string xrefSystemId = 7;</code>
     * @return The xrefSystemId.
     */
    public java.lang.String getXrefSystemId() {
      java.lang.Object ref = xrefSystemId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        xrefSystemId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * {"AMANDA"|"HANSEN" ...}
     * </pre>
     *
     * <code>optional string xrefSystemId = 7;</code>
     * @return The bytes for xrefSystemId.
     */
    public com.google.protobuf.ByteString
        getXrefSystemIdBytes() {
      java.lang.Object ref = xrefSystemId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xrefSystemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * {"AMANDA"|"HANSEN" ...}
     * </pre>
     *
     * <code>optional string xrefSystemId = 7;</code>
     * @param value The xrefSystemId to set.
     * @return This builder for chaining.
     */
    public Builder setXrefSystemId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      xrefSystemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * {"AMANDA"|"HANSEN" ...}
     * </pre>
     *
     * <code>optional string xrefSystemId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearXrefSystemId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      xrefSystemId_ = getDefaultInstance().getXrefSystemId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * {"AMANDA"|"HANSEN" ...}
     * </pre>
     *
     * <code>optional string xrefSystemId = 7;</code>
     * @param value The bytes for xrefSystemId to set.
     * @return This builder for chaining.
     */
    public Builder setXrefSystemIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      xrefSystemId_ = value;
      onChanged();
      return this;
    }

    private long xrefId_ ;
    /**
     * <pre>
     *subsystem personid or caseid
     * </pre>
     *
     * <code>optional uint64 xrefId = 8;</code>
     * @return Whether the xrefId field is set.
     */
    @java.lang.Override
    public boolean hasXrefId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     *subsystem personid or caseid
     * </pre>
     *
     * <code>optional uint64 xrefId = 8;</code>
     * @return The xrefId.
     */
    @java.lang.Override
    public long getXrefId() {
      return xrefId_;
    }
    /**
     * <pre>
     *subsystem personid or caseid
     * </pre>
     *
     * <code>optional uint64 xrefId = 8;</code>
     * @param value The xrefId to set.
     * @return This builder for chaining.
     */
    public Builder setXrefId(long value) {
      bitField0_ |= 0x00000004;
      xrefId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *subsystem personid or caseid
     * </pre>
     *
     * <code>optional uint64 xrefId = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearXrefId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      xrefId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <pre>
     * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
     * </pre>
     *
     * <code>optional string status = 9;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
     * </pre>
     *
     * <code>optional string status = 9;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
     * </pre>
     *
     * <code>optional string status = 9;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
     * </pre>
     *
     * <code>optional string status = 9;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
     * </pre>
     *
     * <code>optional string status = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Person{ACTIVE|INACTIVE}, CASE{QUEUE | INITIATED | EXT_WAIT | INT_WAIT | DONE}
     * </pre>
     *
     * <code>optional string status = 9;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000008;
      status_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
        onChanged();
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
        onChanged();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
            createTime_ != null &&
            createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          createTime_ =
            com.google.protobuf.Timestamp.newBuilder(createTime_).mergeFrom(value).buildPartial();
        } else {
          createTime_ = value;
        }
        onChanged();
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public Builder clearCreateTime() {
      if (createTimeBuilder_ == null) {
        createTime_ = null;
        onChanged();
      } else {
        createTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp createTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private com.google.protobuf.Timestamp updateTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updateTimeBuilder_;
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return Whether the updateTime field is set.
     */
    public boolean hasUpdateTime() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     * @return The updateTime.
     */
    public com.google.protobuf.Timestamp getUpdateTime() {
      if (updateTimeBuilder_ == null) {
        return updateTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      } else {
        return updateTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updateTime_ = value;
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder setUpdateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updateTimeBuilder_ == null) {
        updateTime_ = builderForValue.build();
        onChanged();
      } else {
        updateTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder mergeUpdateTime(com.google.protobuf.Timestamp value) {
      if (updateTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
            updateTime_ != null &&
            updateTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          updateTime_ =
            com.google.protobuf.Timestamp.newBuilder(updateTime_).mergeFrom(value).buildPartial();
        } else {
          updateTime_ = value;
        }
        onChanged();
      } else {
        updateTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public Builder clearUpdateTime() {
      if (updateTimeBuilder_ == null) {
        updateTime_ = null;
        onChanged();
      } else {
        updateTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdateTimeBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getUpdateTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder() {
      if (updateTimeBuilder_ != null) {
        return updateTimeBuilder_.getMessageOrBuilder();
      } else {
        return updateTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updateTime_;
      }
    }
    /**
     * <pre>
     *Output only
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp updateTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getUpdateTimeFieldBuilder() {
      if (updateTimeBuilder_ == null) {
        updateTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdateTime(),
                getParentForChildren(),
                isClean());
        updateTime_ = null;
      }
      return updateTimeBuilder_;
    }

    private com.google.protobuf.Timestamp subsysRefreshTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> subsysRefreshTimeBuilder_;
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     * @return Whether the subsysRefreshTime field is set.
     */
    public boolean hasSubsysRefreshTime() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     * @return The subsysRefreshTime.
     */
    public com.google.protobuf.Timestamp getSubsysRefreshTime() {
      if (subsysRefreshTimeBuilder_ == null) {
        return subsysRefreshTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : subsysRefreshTime_;
      } else {
        return subsysRefreshTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    public Builder setSubsysRefreshTime(com.google.protobuf.Timestamp value) {
      if (subsysRefreshTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        subsysRefreshTime_ = value;
        onChanged();
      } else {
        subsysRefreshTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    public Builder setSubsysRefreshTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (subsysRefreshTimeBuilder_ == null) {
        subsysRefreshTime_ = builderForValue.build();
        onChanged();
      } else {
        subsysRefreshTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    public Builder mergeSubsysRefreshTime(com.google.protobuf.Timestamp value) {
      if (subsysRefreshTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
            subsysRefreshTime_ != null &&
            subsysRefreshTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          subsysRefreshTime_ =
            com.google.protobuf.Timestamp.newBuilder(subsysRefreshTime_).mergeFrom(value).buildPartial();
        } else {
          subsysRefreshTime_ = value;
        }
        onChanged();
      } else {
        subsysRefreshTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      return this;
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    public Builder clearSubsysRefreshTime() {
      if (subsysRefreshTimeBuilder_ == null) {
        subsysRefreshTime_ = null;
        onChanged();
      } else {
        subsysRefreshTimeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getSubsysRefreshTimeBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getSubsysRefreshTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getSubsysRefreshTimeOrBuilder() {
      if (subsysRefreshTimeBuilder_ != null) {
        return subsysRefreshTimeBuilder_.getMessageOrBuilder();
      } else {
        return subsysRefreshTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : subsysRefreshTime_;
      }
    }
    /**
     * <pre>
     *Output only  - updated by person/{id}/xref/{subsysId}/sync
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp subsysRefreshTime = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getSubsysRefreshTimeFieldBuilder() {
      if (subsysRefreshTimeBuilder_ == null) {
        subsysRefreshTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getSubsysRefreshTime(),
                getParentForChildren(),
                isClean());
        subsysRefreshTime_ = null;
      }
      return subsysRefreshTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:corp.model.Xref)
  }

  // @@protoc_insertion_point(class_scope:corp.model.Xref)
  private static final corp.model.Xref DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new corp.model.Xref();
  }

  public static corp.model.Xref getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Xref>
      PARSER = new com.google.protobuf.AbstractParser<Xref>() {
    @java.lang.Override
    public Xref parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Xref> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Xref> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public corp.model.Xref getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

